public class Arte {
    private static final String[] titulo = {
        "                               .::.                           ",
        "                              .;:**'                          ",
        "                              `                               ",
        "  .:XHHHHk.              db.   .;;.     dH  MX                ",
        "oMMMMMMMMMMM       ~MM  dMMP :MMMMMR   MMM  MR      ~MRMN     ",
        "QMMMMMb  'MMX       MMMMMMP !MX' :M~   MMM MMM  .oo. XMMM 'MMM",
        "  `MMMM.  )M> :X!Hk. MMMM   XMM.o'  .  MMMMMMM X?XMMM MMM>!MMP",
        "   'MMMb.dM! XM M'?M MMMMMX.`MMMMMMMM~ MM MMM XM `' MX MMXXMM ",
        "    ~MMMMM~ XMM. .XM XM`'MMMb.~*?**~ .MMX M t MMbooMM XMMMMMP ",
        "     ?MMM>  YMMMMMM! MM   `?MMRb.    `MM   !L'MMMMM XM IMMM   ",
        "      MMMX   'MMMM'  MM       ~%:           !Mh.''' dMI IMMP  ",
        "      'MMM.                                             IMX   ",
        "       ~M!M                                             IM    " 
    };

    private static final String[] CHARMANDER = {
    "              _.--\"\"`-..",
    "            ,'          `.",
    "          ,'          __  `.",
    "         /|          \" __   \\",
    "        , |           / |.   .",
    "        |,'          !_.'|   |",
    "      ,'             '   |   |",
    "     /              |`--'|   |",
    "    |                `---'   |",
    "     .   ,                   |                       ,\".",
    "      ._     '           _'  |                    , ' \\ `",
    "  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|",
    "  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\",
    "-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .",
    "  `,         \"\"\"\"'     `.              ,'         |   |  ',,",
    "    `.      '            '            /          '    |'. |/",
    "      `.   |              \\       _,-'           |       ''",
    "        `._'               \\   '\"\\                .      |",
    "           |                '     \\                `._  ,'",
    "           |                 '     \\                 .'|",
    "           |                 .      \\                | |",
    "           |                 |       L              ,' |",
    "           `                 |       |             /   '",
    "            \\                |       |           ,'   /",
    "          ,' \\               |  _.._ ,-..___,..-'    ,'",
    "         /     .             .      `!             ,j'",
    "        /       `.          /        .           .'/",
    "       .          `.       /         |        _.'.'",
    "        `.          7`'---'          |------\"'_.'",
    "       _,.`,_     _'                ,''-----\"'",
    "   _,-_    '       `.     .'      ,\\",
    "   -\" /`.         _,'     | _  _  _.|",
    "    \"\"--'---\"\"\"\"\"'        `' '! |! /",
    "                            `\" \" -' "
    };


    private static final String[] HO_OH = {
        "        .:.",                                                                                                                           
        "       72riL.",                                                                                                                         
        "        r1:ii27      :",                                                                                                                 
        "        Ki:i.7r    IPq7",                                                                                                               
        "    :.  .1:.. :7   gvvb",                                                                                                               
        "    L:Y7  ii   .:i  Zr7b.",                                                                                                              
        "27i:7s: i  qq7.. brrK:",                                                                                                              
        "r1:i::r7..:ZrI7.:5r7vu",                                                                                                              
        "    :j:::. r7r17r5:.gLJuX",                                                                                                              
        ".  .L:.   .uZ77r5.LUsSb:",                                                                                                             
        "S7r  v.     jZr7711K7SUU",                                                                                                             
        ".X:r7: i    : .5rLvdRLjX5.",                                                                                                            
        ".5:i::r:7. vZj:.27s7d1vRI7",                                                                                                            
        ".77::..:srB77Ji7UvJL27bbJ.",                                                                                                           
        "    .Lr.   7QYr77sXIY1suLBL2",                                                                                                           
        "rr. :i.   .5Ur77IBXL1jJbdL:",                                                                                                          
        "sv7v:iii    u5rYLIDXL1JuMYq",                                                                                                          
        "7r:ir::7Ii   iqJuYsXbsuLqqU5",                                                                                                         
        "77r::.  LYYi  s5ussU5YJLQsP7",                                                                                                        
        "    :7r.   LDUI7.ijjLsLjYL2MLM.                                                ..,",                                                     
        ":i::vL.  :Zrr72Yj25LJsjsYPKjg.                                            .:ii7vY",                                                   
        "2J:riLusi..jJ7rJu1dgusYjYYb1ID                                          riLZ.7USD",                                                   
        ".K:::...ijr:r7jLYLssXK5YjLjbjSZ                                       iri.jMv:7jY",                                                   
        "    .ir7i.   .Zv7LIU1vLvj5UYjL1b1b5                                     7i:7Li:r7.::s",                                                  
        "    .ir:  .K77771bMSuvYLuJuLU2jbj                                  :L:ivri7i.rL:7S.         .",                                       
        "    Ki:ii77i.J1jrr7L1Pqq1usjsjYjJ1ES                                 :27rKvr.LiiXY1d      .i::iu5bu.               .i",                 
        "    S7:ii:::r77rLYjLL7YJI22YusuJjujbS                                 .:::rUviI7Ii1     :i:..jBBBPqi              :XE",                 
        "    KL7i:.    . :rsju7L7sYjYjsjL25LXP                                     .PJXdQXv..77i:::LDBBj                 75us",                 
        "    ..iir:.  gu7rrJXMPSJJYjsuYJYDKLSI                                     7RK:uQBBi:7JbDBBBQr                .SULE:",                 
        "        ...:iii.UB7r77J1XPq5XJjJjL5IMPL1K:                                  .DDr  uKu5gZZZM5i.                 rbuuMK.LbbR",             
        "        Eviri:.. L5IJ1suYsLjj1JuJJUXIMKJubi                                .2jIBQMb.:r7SZDb:     .            5MIqQs  :JSj",             
        "        .Prii::     .:7YuJ1YYLssu5PIXSDD1YSL                               dSLsJuJX7:...:ir7uvJSb7          7BRXPd.  iIU.",              
        "        .i::ii7:   J7i7Yjs5qb52121SIq5Eg5LU2.                            :MU1JjsJJZ5Js5JJLjIbXr          :QBDIKQUiP.71D.",              
        "        ..::i7iriBu77sJuJ112u2155SXKSqMbYsUr                           2X1juJuLj2MBB:.vKJi.          .KBQPUKKdqXbiLbL",               
        "        b7:iiii. .B1Js1uusJLLvuISIqXKSKDM1L1I                         .b2susuUbMBQd                .PQBEXSbbq1uIs::",                 
        "            IYi:ii:   :::i77Ls2S2j1UKXKSK5XPMXYjK.                      .bqU2XMQQEKv.               .XBBMKSqERR2j::iL:",                 
        "            iLLi777.   .::7Yu2PU1sjIKIK5XISSME1YbL                    vDKj1MDi.                  .bBBgbU5ISXPKbZ: rSg",                 
        "                ...:iii:bbL7ssJLJYLv1US2KSK5X2bgKvXb:                .r::..ur                   rbBBMq5XbPZdKjLJ7.:J2.",                 
        "                YXirii.  r1Jv7Y1jU5PSXbb5X5XSXIKgZYjE1             iSILL7uBr                 :5BQBDbIXIbPdEdvi  7qJ",                    
        "                :1Lv7i.  .r7viijU5112K2I2KSK5KSSdR2Yqb.         .qXvJXU5Qg                rDQBQgX5IKXqSb5qbqDv.LqK",                    
        "                .:::rvY:. rqL7YLLL11KKbbb5XSX55SMbsjPL7.   .rSE1YJ1LJKB:             iPQBBRbXUKSqSX5SERrrsL:1Kv",                     
        "                    I7i:.   .25J1qZPq2ujS2SSqSqXXIMgjsjL12gbMP5j1JJvjKBD          :LEQBMMdPU55XSX5Kbb5UUq .LJ",                        
        "                    .LLvi7s1:...sbvLLjYuUqqXIS2X5K2BZjsj77SZJjLsLYsUXDj       .7qQBBgbqP5X5KSqSS2SIgLK5K17j2L.",                       
        "                        .LYLi.   .v2U2L1qDqPSS15I52SqB2jj2jsJ1sIU5USbQv. . .rXgBBBgDbqSKSqSK55ISKDSSU1 .7Yi7,",                          
        "                        .27r:L17:  : rI1Jj5dSEPS5KPRgbSK2UJjsJ2bSqXBZDBBQBQBQQRREd255XSK5X2XKS55X21uu:rIb",                            
        "                            .7U7r::.   .i7uUqL1bqSqRMrii7sKPKuUJJqb1ggEZQMQQBRRZEqK5SUK5KKZIXUDg2jZ..:Pd7:",                             
        "                            Jjv7r7UPi   .. .dKbMQI       i5P1Us1qPRQgMDDdbbbbPSq5XXgSK5qddIISEir:Js2L.",                               
        "                            .i :L7::...:.   .uIr   . .    sb1jLSqDgbPdbZdDEdKb5qSbbqKK2d7Yi:::rbZ:",                                  
        "                                .U7rirqqi..  :     ..... .  LdI5PPEBbEbdPDPPSXMbXX2bYjs7: .:rB517",                                    
        "                                    i7:sL.::7j7. ...... . . .  ijSEquEqSXSKPMIXIb5I5uJr ..7bSbM:",                                       
        "                                    Ri::YY:  ..............   ir::QSqQXIbbS1jY7 i..XQuDZv:.",                                         
        "                                    Dq..i.      . . .......  .:::.2gXSMX5J: si..bM2bI:i.",                                             
        "                                    YQ     .  . . . . .   .  .rii:i5r:: i5::rdPKgY..",                                                  
        "                                    Qi  .ri.       . .     ..::ri:5sqrv2EBjbZ. .",                                                      
        "                                    .b:.rL     .           ::::iiiKEUbvJr  .",                                                           
        "                                    .7:XL.        r   ...:i:::i:iJ:",                                                                    
        "                . .........      .7ui.::.   ...U:.iiiiiirii:rv",                                                                      
        "                7br77LvYjqZgZMZg5Y:jqr.PbIuX5i::rb:iiiiiii::.7M:",                                                                      
        "            .d21255vLjSI512jUJLrrsb7BMSYQJUb7isi:iiii::::iSuK",                                                                       
        "        .:7vv7rL2j:::ir77rr7r7vJ7is5jBBqSQbULbXBSi:i:::::75b1di",                                                                       
        ".:iirrvri:rrqbL.....:iLJ1s1JUjs7sJBBMUPDXPdDXMD77rririJU11di",                                                                        
        ".:r::.::::rL2JLi:P2iLsUJ1s1UKIuj25Iv.dBEZBEI5ZgDB5bdPYLqMsL7:",                                                                          
        "7u.     :rLL7::::.:r7LuuU5qKXUUu2JJ7:.1QRQBRBBBRR7.rs7IQBBRMIri.7i",                                                                      
        ".r:  .:r77r:i:::::r7vLjssjsLJJUsY77iLI2iMM7PbJPu7     LQDbKMDDDdS2DP",                                                                     
        ":ui7Li: .:::7717r7jsLrirLu1YY77r7v5Ssi725u1.i:.v     YBBM  UZSEbjRBL",                                                                    
        "sL    .:r7 rbr7j7i.:7j7i.rLLrL2qs7i5g7iiXrPLLJ      2dvZiDdqEBSQBB.",                                                                   
        "r. .:7r.   7X7i:::Sji:::rri7XIu77rdB7r77KiZrI7          BBBQBBBBBE.",                                                                   
        "iubi.   .7r::i:i:LZ:.::::rsXY7777Dg77LiK7sKiU7           v7rJi",                                                                        
        "    ir: .iriri:JUiS77jIIj7L77JMb77Lrsq:X1rK.",                                                                                        
        "    .rr.  ::iii:i7svLQIv7i7LLrubZU777rrPviSr72.",                                                                                        
        "7:        ::: Ldv7i:::rY77EqULi77riuJr71irX",                                                                                         
        "5... ..:i:.   :7:.::::i:7bv7L:7i.:UYi:Ds.7L",                                                                                         
        ".:E7ii:.   .r:.  .iii:iUdi:P.::.rSJ.:7K.7g.",                                                                                         
        "            .7r.  ..ir::vR2:::Er:7bM7.:LrsUvv",                                                                                          
        "        7i.   . ...:7i7::::r2sD::.:U:  .",                                                                                            
        "        i7   . .   .rL..:..:i..J::.:q:",                                                                                                
        "        rL      ..ir:     :i .i.. .2.",                                                                                                 
        "        ir.:. .::i:.    .7: ::   .Y.",                                                                                                  
        "        ..I1i:.:     .77  ri  i7i " ,                                                                                                  
        "                :U..77rr.   5r7:::",                                                                                                     
        "                ....i       i."   
    };    

    private static final String[] VULPIX = {
        "               _,.+-----__,._",
        "              /  /    ,'     `.",
        "     ,+._   ./...\\_  /   ,..   \\",
        "     | `.`+'       `-' .' ,.|  |",
        "     |  |( ,    ,.`,   |  `-',,........_       __......_",
        "      \\ |..`/,-'  '\"\"\"' `\"\"'\"  _,.---\"-,  .-+-'      _.-\"\"`--._",
        "       .\"|       /\"\\`.      ,-'       / .','      ,-'          \\",
        "      .'-'      |`-'  |    `./       / / /       /   ,.-'       |",
        "     j`v+\"      `----\"       ,'    ,'./ .'      /   |        ___|",
        "     |                      |   _,','j  |      /    L   _.-\"'    `--.",
        "      \\                     `.-'  j  |  L     F      \\-'             \\",
        "       \\ .-.               ,'     |  L   .    /    ,'       __..      `",
        "        \\ `.|            _/_      '   \\  |   /   ,'       ,\"    `.     '",
        "         `.             '   `-.    `.__| |  /  ,'         |            |",
        "           `\"-,.               `----'   `-.' .'   _,.--\"\"\"'\" --.      ,'",
        "              |          ,.                `.  ,-'              `.  _'",
        "             /|         /                    \\'          __.._    \\'",
        "   _...--...' +,..-----'                      \\-----._,-'     \\    |",
        " ,'    |     /        \\                        \\      |       j    |",
        "/| /   |    j  ,      |                         ,._   `.    -'    /",
        "\\\\'   _`.__ | |      _L      |-----\\            `. \\    `._    _,'",
        " \"\"`\"'     \"`\"---'\"\"`._`-._,-'      `.              `.     `--'",
        "                       \"`--.......____:.         _  / \\",
        "                               `-----.. `>-.....`,-'   \\",
        "                                      `|\"    `.  ` . \\ |",
        "                                        `._`..'    `-\"'",
        "                                           \"' ",
    };

    private static final String[] MAGMAR = {
        "                                                 ,--''''-.",
        "                                               ..    `'  `",
        "                                                '    .'...'",
        "                                            '  ,'::     |",
        "                                               ,..-Y-'  /--",
        "                                    .              |' _.'",
        "                                  .' .______ ,-'\"|  ,'",
        "                           /,  ,. '-'     .-' .\" | '",
        "                          /  \"'  ' -=L;'\\'    `-.'.",
        "             ,,          /__       ],L_/'        .'            |\\",
        "       |`.  '\\  _,          |         .        ,'          =-. `|",
        "       `. ,' |.`            '`-v      `'-.    |             | -,..",
        "        _:  \" `\\,.     ___    _'|  ,-,_-  `-..'          .]---> _`'",
        "      . ___.   ' /'--.  -.=[----`, |   '-  ,'                | </",
        "             ]..b--`. -'- , ----`` |'--v -'            __-- ' ,,",
        "            .'|    <\\]``,[ -    '\\\\._  |'  '''`- _  _,|    `''|",
        "   \\\" ''L     |   X`.  ` /--,    |  -`.:_ `.    ' TX_,.:'..  ,|",
        "   `   |       \"` =. ----  _|    |      ` _ `\\ |=:| /   '-\\ --'",
        "   |.   `.          '''-..L    _,'      .' `,.``-() Y.-[ .'",
        "   '    .            _. _.. -]-,..-,'    v.   \\|  ` '`'",
        "`.'       `.        ' ---.'- /-[  .',_   -.   ,)L",
        "  |       .'      __,...-`=..__       '   '     '.",
        "   ,\"', .'      -`... _-'      `.     ` ,'      | `.",
        "       .`            .'          .     '        |   \\",
        "         '           |           |             .'    .",
        "        \\ `.         '           '            ,'     |",
        "         \\  `.        `         /           .'     _.'",
        "          '.  `-.     /`__    ,'.._______,-'--...-` `.",
        "            `.   `--..'J  \"'.'         ,'       `._\\` ``-...",
        "              `.   .'   `'|'        _,'          |    _    \"-.",
        "                `.'|  ..  |     _,-'             `-._| '.---.'",
        "                / _,_/  |-`---\"'                     `-..|",
        "               `-\"   | .'",
        "                     -'"
    };

    private static final String[] PIKACHU = {
        "                                             ,-.",
        "                                          _.|  '",
        "                                        .'  | /",
        "                                      ,'    |'",
        "                                     /      /",
        "                       _..----\"\"---.'      /",
        " _.....---------...,-\"\"                  ,'",
        " `-._  \\                                /",
        "     `-.+_            __           ,--. .",
        "          `-.._     .:  ).        (`--\"| \\",
        "               7    | `\" |         `...'  \\",
        "               |     `--'     '+\"        ,\". ,\"\"-",
        "               |   _...        .____     | |/    '",
        "          _.   |  .    `.  '--\"   /      `./     j",
        "         \\' `-.|  '     |   `.   /        /     /",
        "         '     `-. `---\"      `-\"        /     /",
        "          \\       `.                  _,'     /",
        "           \\        `                        .",
        "            \\                                j",
        "             \\                              /",
        "              `.                           .",
        "                +                          \\",
        "                |                           L",
        "                |                           |",
        "                |  _ /,                     |",
        "                | | L)'..                   |",
        "                | .    | `                  |",
        "                '  \\'   L                   '",
        "                 \\  \\   |                  j",
        "                  `. `__'                 /",
        "                _,.--.---........__      /",
        "               ---.,'---`         |   -j\"",
        "                .-'  '....__      L    |",
        "              \"\"--..    _,-'       \\ l||",
        "                  ,-'  .....------. `||'",
        "               _,'                /",
        "             ,'                  /",
        "            '---------+-        /",
        "                     /         /",
        "                   .'         /",
        "                 .'          /",
        "               ,'           /",
        "             _'....----\"\"\"\"\" "
    };

    private static final String[] AMPHAROS = {
        "                                                                 7v7i.",                                                                                
        "                                                                UsMBQBgs",                                                                              
        "                                                               2E .   .iL:",                                                                            
        "                                                              .B.  ..rj2ubY            .:YL7irri",                                                      
        "                                                              7I .:vXgBMQQBL        s5i.Usi7IbMBB",                                                     
        "                                                              :Y:M1JKQMDMBQQ.:::..7db.  ::jdbbqMB",                                                     
        "                                                               7BBBSX5SSJ.. .....K5U.   BBgqqKqMb",                                                     
        "                                                                Q5  .viLu  ..:. vEr:  ..:DRBRMgB.",                                                     
        "                                                                i7..iLL7q...:...7KPMS    .LJ1JY7",                                                      
        "                                                                JUUULr7b:......:.bMdgU....   .i",                                                       
        "                                                               7ZS2JLvv:......:. :BMZQBbs::LIi",                                                        
        "                                                              i..Lr7:.  .  ...... .bQBQBBBBS.",                                                         
        "                                                             7. .   ... iL7 ......  :72jr:7",                                                           
        "                                                            ri .......iB iBb .......     .i",                                                          
        "                                                            L ....... :QBQBD ............Y.",                                                           
        "                                                           7. ........ .22r....:.:.:...:ru",                                                            
        "                                                           7 .:.:.:.:..    ...........:iS",                                                             
        "                                                          .v :.:.:.:.:.....:.:.:.....iij:",                                                             
        "                                                          :J ...:.:...:...........::ii7v",                                                              
        "                                                           5.....:.:.:...... ..::iiriivi",                                                              
        "                                                           7i.............i7v77iririi:J:",                                                              
        "                                                            7rii:::iir7vvJX1Lsriiiiiii77",                                                              
        "                                                              ...::::.:.     .Uiririi:i7",                                                              
        "                                                                              .Y :::.. 7",                                                              
        "                                                                               vi . ..vB:",                                                             
        "                                                                               ig.ZBQBBD7",                                                             
        "                                                                               :b rYYr:rQ",                                                             
        "                                                                               .Z rvvuXQQ.",                                                            
        "                                                                               .q KRgbKL2L",                                                            
        "                                                                               :u.ii:i:7bB",                                                            
        "                                                                               jKLdMMgQBBQ.",                                                           
        "                                                                               L:72ZPb51i:i",                                                           
        "                                                                              7:    ......7.",                                                          
        "                                                                             .7  ..r:. . iLI",                                                          
        "                                                                             7. ..Y.       7I",                                                         
        "                                                                            i: ..Y.         IY",                                                        
        "                                                                ..:.:::irrivi...7i           ES7sLJsLLLii:.",                                           
        "                           i.iUSL:                       ...:rr7rrii::::::::...:J             P::iir:iri:rr7i7r:",                                      
        "                          P7 .YJ2b7                  .iiiii::.............. .i.1.             ss:iiii::.......:i7ii:.",                                 
        "                         1SuuJvL7Yb               :7ri:..........:...:.....r1.rr               d77riii::...........:iri:",                              
        "                         YgjuLsiiLd            .r7i.. ..................:ru7.:7                .r.7JYri:...............:ri.",                           
        "                          :SjgBIrJ           :ri.. ................. :isvi...u                  i   :vv7:............... .::.",                         
        "                            .bBS           :U:. ............. ...:i:XLi.....2.                   J     .:r7rri:::.:.:.:.::::q:",                        
        "                             1Qd           .::::::::.:....:::ii77i.ir......L:                    .Y         .::ri777r7rr::..",                          
        "                             JBBi              .:.::::i:::::..    :i......7i                      rr",                                                  
        "                             :BKB                                rr......iL                        5.",                                                 
        "                              BiZD                              ri......:u                         :S",                                                 
        "                              E:  :                            vi....:..j.                         .vi",                                                
        "                              :7.LDK                          rr..:....Y.                          :.q",                                                
        "                               QBjRBM.                       :v.......Y:                          .:.rL",                                               
        "                                BQb777.                     .I..:.:..7:                           :::.DL",                                              
        "                                JB    r1:                   b7.:...:7.                           .::..ibY",                                             
        "                                 j: rDQMBg7.              rri...:..LY                            .:::.iJ7U",                                            
        "                                  sLBd5KPBBBDL.          7r.........r.                          .:::..:K.J7",                                           
        "                                  .BBbPPML:..:i:irii:::7L. .........:L                         .:::.:.:1:.I.",                                          
        "                                   :QMDQ.  .......::::7U.............L:                      ..:::.:..:I:i:I",                                          
        "                                    :BBL.::..........:Y ..........:..:L                     ....:::.:.7Y:i:Li",                                         
        "                                     :Bs.i:i::...... j.........:.:.:..s                    ..:.:::::..s7:iiiJ",                                         
        "                                      .E7iiii:i::::.r7 .......:.:.....J                 ..:.:.:::::...K:iii:1.",                                        
        "                                        Jjiiiiiiiiiib. ...............J:             ..:.:.:::.:.:.: Lv::i:iLi",                                        
        "                                         :u7iiiiriiiD ..........:.....7        ...:::::::::::.:.:.:.:I::iii:Yr",                                        
        "                                           7J7:iii:vS .....:.:........s:.:.:::::::::::::::::.:::.:..Kr:iii:i1r",                                        
        "                                            .LU7i::7L ....:.....:.:...v::::::::::::::::.:::::.:.:..27:iiiiii5",                                         
        "                                              .v2uiY7 ...........:...:7..:::::.:.:::.:.:.:.:......J7:iii:i:q:",                                         
        "                                                 ijPb ...............Y:.:.:.:.:.:.:.:.:.....:::.is7:iii:iiXi",                                          
        "                                                   .E7::........... ii...:.:.:.:.:.:.:.::r77i::uXY7riiir7q:",                                           
        "                                                    :5i::::........sL.::::::::::::i:iirrv7L77j51LLs777vuK",                                             
        "                                                     1:iiiii:iiri7qUr7rririr:i:i:i7L7L7L7vY1bgqUvYLsLsJq",                                              
        "                                                    .Uiiiiriri77UEuJ1sJLL7v7v7v77777vLsJjLi   .LIvL7Y7j1",                                              
        "                                                    LviiiiirrY7.   :i77uJuuIjJLJJjYu7r:.        2svLLYLI2i.",                                           
        "                                                   .U:iiiii7L.                                 .ELL7sLLY22SJ7:.",                                       
        "                                                  :uiiiiiiJi                                    qKYJLririi:::ir77:",                                    
        "                                                .7JiriiiiL:                                      JE2viri:........:7:",                                  
        "                                              .Yj7iiiiii7r                                        :Luu7i....... .::7U",                                 
        "                                             iv:....::::s:                                           :LYr::::..:v .iu",                                 
        "                                           .7: . . .....iu                                              .::iirr2277i",                                  
        "                                           P. ...........1.",                                                                                           
        "                                          :s ... ........ri",                                                                                           
        "                                           L7...ii:.ii...1i",                                                                                           
        "                                            :7UX:....qYir:",                                                                                            
        "                                                ::::i:."  
    };

    private static final String[] DEDENNE = {
        "                                  _,._,._",
        "                                 '-\"._,\"--,",
        "                                  `\"..-+-'",
        "                                  :'==-:",
        "                                  :`=-\":",
        "                                 _.\"-..|",
        "     _____                  _.-'\"  `\"\"' `-._",
        "    |  |  `\"\"'----._      ,'                `.",
        "    |__|            `.  ,'                    '.",
        "    '..|\"\"'---._     | /                        \\    _.......______",
        "          `\"\"\"--:    |/         ,.---._          \\ .'.------.....__`-...",
        "                |    j        ,'       `.         . '              |\"--|",
        ".'\"\"|\"---......-'   .|       /           \\        |'     ______    |   |",
        "|   |              / |      .      .      .       |    .'      `\"\"`--..'",
        ":\"\"'|---.....___.-'.'|      |             |       |    :",
        " `\"`+---....____,.'  `      `.           /       /|    '_",
        "                      \\ _,..  `.       ,'       / `      `\"\"'--....,._",
        "                      .'::__:   `-...-'        ,   `._            '   |",
        "                      |-..--|          ,-\"-. ,'       \"--.....___:   j",
        "                      `.::_,          |.-''-:                     `\"'",
        "                            `\"-...____' \" :.'",
        "                                       `\"\"' "
    };

    private static final String[] JOLTEON = {
        "XH                             HX               ",
        "H;XHX                         HXH               ",
        "H;;;;XH                      XHXH               ",
        "XXXX;;;H                     HX;H               ",
        " HXHHX;;H                   HXH;H    XH         ",
        " HXXHHX;;X                 HXXH;H  HX;H         ",
        " XXXHHHX;H        X  H     HXHX;HHX;;;X         ",
        "  HXHHHHX;H       HH HH   HXHH;;X;;;;X       XHX",
        "   HXHHHHX;X XH  XXXHHXH  HHHH;XHX;;;H    XHX;;H",
        "    HXHHHH;;XHXH HX;XHX;HHXHHX;H;H;;XXXHHX;;;;H ",
        " HHHXXXHHHX;;HXXXHX;;XHXHXHHH;;;XH;HXXX;;;;;XH  ",
        "  HXXXXXXHHX;;H;XXX;;;HX;HHHXX;XHHHXX;;;;;;XH   ",
        "   XHXXXXHHXX;X;;XXX;;;X;XHHXXH;;;HX;;;;;XXH    ",
        "     HHHXXX;;;;;;;;X;;;;;;XHXH;;;HX;;;;;XXH     ",
        "      HXHXXX;;;;;;;;;;;;;;HXH;;;;HX;;;;XXH      ",
        "       XHHX;XHXX ;;;;;;;XXXH;;;;HX;;;;XX;;XHX   ",
        "       HXXH;;HH X ;;;;;X H;H;;XHHHHHHXX;;;;;;HX ",
        "     XHX;HX;;XHHHX;;;;XHHX;X;;;;;;;  H;;;;;;HX  ",
        "  XHX;;;HXHX;;XHHH;;;;HHX;;;H;;;    H;;;;;HX    ",
        " XH;;;;;XHXH;;;;;;;XH;;;;;;XH      HXX;;HX      ",
        "   XHX;XHXHXX;H;;;;;;;;;H;XHX    HHXXXXX;;XHHHHX",
        "      XH;;;HHXXHHHHHHHHH;XH    ;;  HXXXXXXXX;;H ",
        "     H;;;;;;XX;XHHXXXXHH;H      H;; HXX;;;;;;H  ",
        "   XH;;;H;;;;HX;HXXXXXH;X        HHHXX;;;;;;H   ",
        "    HHHX;;;;;;H;;HHHHH;XH   ;;    HXXX;;;;HX    ",
        "      H;; ;;;;;HX;;;;;H     HX;;   HX;;;XHH     ",
        "     H;;   ;;;;;;XHHHX      XHHX;;  H;XH;;H     ",
        "    H;;    ;;;;              HHHHHHHH;H;;;XH    ",
        "   H;;   XHX;;;        X;    XHHHHHXXXX;;;;H    ",
        "  H;;XHHXH;H;;  H;     XX;    HHHHXXXXX;;;;XH   ",
        " XHHHHHHHXX;;  ; H;     HHX;  XHHHXXXXXX;;;;XX  ",
        "        HXH;   H; H;    HHHX;  HHXHXXXXXXX;;;H  ",
        "        HXH   HXH; H;   XHHHHX; H   XHHXXXX;;;X ",
        "       HXXH  HX  H;HH;   HHXXHHHHX     HHXXX;;H ",
        "       HXX;HHX   XH;;H;  HHXXXXXHH      HXXX;;H ",
        "      HXX;;HH   HXX;;;H; H HXXXXXX       HXX;;X ",
        "     HXXX;;H    HXX;;;XH;H HXXXXXH       HXX;;;X",
        "    HXXX;;X     HXX;;;XXHH  HXXXXH       HXX;;;H",
        " HHHXX;;;XH    HXX;;;XH  X  HXHXXX       HXX;;;H",
        "HXXX;;;;;H     HXX;;;H      XHHHX        HXX;;;H",
        "HX;HH;;HH     XXX;;;;H                   HHX;H;H",
        "HH;H;XHH      HX;;;;XX                   XHX;H;X",
        "  HHHHX      HXX;;;;H                     XHHHX ",
        "           XHXX;;;;XH                           ",
        "           HXX;;H;;H                            ",
        "           XH;;H;;XH                            ",
        "            XH;H;XH                             "
    };

    private static final String[] BAYLEEF = {
        "                      _____         ____",
        "                   ,\"'     `.   ,-\"'    `\".     ,.",
        "                  .  ,---.   |,'   _...    .    | `.",
        "             _.---'`'\"-._ |  /   .'.---`.  '    '  |",
        "           ,'            `| /...-._____ |  |`\".'   |",
        "          /    _,---+-.   ,'       `-. ||  '   `..-.._",
        "         .   ,`._    `.`,'.   _...    \\` .  `.   `.   `-.",
        "         |_,.-...`---\"'|  ,`.|  .\"`    \\`.`.  `.   \\     \\",
        " ,      ,'             |  |  |  |  \\    \\ `.`._ `.  \\`.   .",
        "| \\    '     __......-\"|  |  |  |`._\\    '. `\"-`. .  . \\,\"'-._",
        "|  `\"'|   .\"'   ___    |  |  '  `-...\\...|_`.._ | |..:-'      `.",
        " `-..-|  .    .\"  _`+.,'  |   `._          `-.,'  |     ,+\"|`. |",
        " ,'  ,|  |  ,' ,\"'     __,'      `'\"\"\"\"'`-.   .  ,'...-' | | | |",
        ".   / `  |  | .   ,-'\"'             ____   `. |-'-.| |   ',' `'",
        "|  |   \\ |  | | .'   ,-'\"\"'-.    ,'\"    `.  | |.   | |__     ,.",
        "'  `.   `|  ' | |  .'        \\  .         | | `.`. '  . `\"-.' |",
        " \\ |\\`-..|   .`.|  |    ()    | |   ()    ' `._ ,.' \\  `---' ,",
        "  `| `--\"    | |   '          ' '        .    .' |   |.____,' \\",
        "   `.       ,' '    `.     _,'   `. ___.'_..,'   |   |  | `.   .",
        "     `-...-' .' _...  `---\" _....._  _.'\"    `..'|   |  |  |   |",
        "    ,'    _.\" ,'    |    .-' ___   `'   _..    `/|   |`.|  |   '",
        "   '    ,'/  /   _,.'  ,' .-'   `\".  \\,'   `.   | .  `  .  '  /",
        "  .   ,` ' .'   '    |/  /   ____/ \\  . ,-\"'|   '-.`.__,',' ,'",
        "  |   | |  ||  |`-..\"/  /`.'\"   /   . |'  _,'  /.  `. .\"' .'`..__,.",
        "  `   `.|_..'  `._  /  /   `._ /   /| | ,'/   /  \\   \\  ,\"._    _,'",
        "  ,`.        \\    `-._/ `.    `-.,' | |. /  ,'   /.   \\'  __`--\"",
        "  |  |-..,.\"| `-._    `.  `,      \",  '-j  .   ,',`.   `\"'  '",
        "  |  |   `. `-../ `-.   `.' `\"+-..' .'  |  |_,'.\"| |`.   _,'",
        "  '   `-._ `._.'   / `.  | _,'  |\"'|`-..|  |   | | |  `\"\"",
        "   `._    `\"'   _.|__.-| |\" `---|  '.   |  '.,'  `.'",
        "      `-.....-\"'  |___,  '       `. \\`+-`.   `.",
        "             .'   '  /  /          \"'/    `\"--'-._",
        "           _,:  ,'   `-\".           .             `._",
        "        ,-'   `\"         |          |                `.",
        "      ,'                 |          '                  `.",
        "     /                 _,'           `._                |",
        "    |               _,\"                 `-..__        _,'",
        "    `.        __..-'                          `\"\"\"`\"''",
        "      `-----\"' ",
    };

    private static final String[] TREECKO = {
"                            ,.--\"\"+`-,",
"                    ___,..-'  C'  `.' `-.",
"                 .\"|      `-,...._   ___:.",
"                /'\"|   _,..^..__ _'\"'     `-.",
"               ' `\" ,-`c.   ..  `.     ,\"\".  `.",
"              /,  ,'       `._'   `.|)  \"'    /\\           .",
"          _,.|'- /  .-.             \\         `\".          |\\",
"      _.-'   |  |   '-        _     |           |          | \\",
"    ,'       |  |            \\.'    |           |          |  .",
"   ,          . |                   |           j          j  |",
"  /_.-'\"\"\"'\"':.+|                   |          /         ,'   |",
" /'       ,-'    \\                 /        _,'-..___,..'     j",
"j|       /        `.             ,^.......-+                 /",
"||      /     _,-.\"\"'-..____,..-'-._        \\               /",
"| \\   ,|    ,' .'   ,'    .         `.       \\__         ,-'",
" . `-'.|   /  /  _.'       `.         \\       . `---+.-'|",
"  `._, ' j   j '\"            `--..     `.     |.     `. |",
"        .|   |                           .    ||       `|",
"        `'   |,----......__...._         '    ||        |",
"             |`._=-=====___''-. `-.      |   / |        '",
"          _,.L   `\"\"\"------|  .---'      |  /`-+_",
"     ,'\"`/    \\            |  |          |.'.    `\"\"'-.",
"     |   \\__,.'`           | j              _+-._     |",
"     |    `     `._        | |             ,     `---\"",
"      .    `...,-' +._      `|            /",
"       `.       -'\"   `-...________,..--.  `.,..",
"         \\     |                         `.     |",
"          `._  |                          '    /",
"             `'                      _,.-'    /",
"                                  ,-'        /",
"                                 `.       _,'",
"                                   `'----' "
    };

    private static final String[] SHAYMIN = {
        "                _.--\"'\"\"\"--._",
        "              .\"             `.",
        "             /                 .",
        "            j                   .",
        "            |                   |",
        "            |                   |",
        "            | (')              j",
        "            `                 ,`.",
        "             \\               ,^. `.",
        "              .             /   \\  .",
        "              |            /     . |",
        "              |          ,'      | |",
        "             ,'---..___ /        | |",
        "            ' `--..___ \"`.      .  |",
        "             `\"--....___.'     /  j__.....__",
        "                              /   |         `.",
        "                             / _,------._     `.",
        "                            /,+_         `.     `.",
        "                          ,'    `-.        \\      .",
        "                         .         `.       \\      \\",
        "                         |           `.     |       \\",
        "                         |             `.   |_,..__  .",
        "                         |\\              \\  |      `.|",
        "                         | `.,--------._  \\ |        `",
        "                         |  |           `. \\|",
        "                         |  |             `.|",
        "                         |  |",
        "                         |  |",
        "                         |. '",
        "                        .' \\ `.",
        "                     _,' ,' `. ._",
        "   ---====+,______,.\"_.-'     .  `.",
        "   _,..==`'_.+'-\"\"\"\"'         / ^.\\`:._",
        " ,=\"/    ,\"            ....==+ /  `\\  `:.",
        "'  /    / |               _+:-'    .|   ``.",
        "       '  `.           --\"\"        |'     `\\",
        "                                   ' "
    };

    private static final String[] BULBASAUR = {
        "                                           /",
        "                        _,.------....___,.' ',.-.",
        "                     ,-'          _,.--\"        |",
        "                   ,'         _.-'              .",
        "                  /   ,     ,'                   `",
        "                 .   /     /                     ``.",
        "                 |  |     .                       \\.\\",
        "       ____      |___._.  |       __               \\ `.",
        "     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\",
        "    .  ,            __               `              |   .",
        "    `,'         ,-\"'  .               \\             |    L",
        "   ,'          '    _.'                -._          /    |",
        "  ,`-.    ,\".   `--'                      >.      ,'     |",
        " . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'",
        " ||:, .           ,'  ;  /  / \\ `        `.    .      .'/",
        " j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /",
        "/ L:_  |                 .  \"' :_;                `.'.'",
        ".    \"\"'                  \"\"\"\"\"'                    V",
        " `.                                 .    `.   _,..  `",
        "   `,_   .    .                _,-'/    .. `,'   __  `",
        "    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .",
        "   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |",
        "  .   _  `\"\"'--.._____..--\"   ,             '         |",
        "  | .\" `. `-.                /-.           /          ,",
        "  | `._.'    `,_            ;  /         ,'          .",
        " .'          /| `-.        . ,'         ,           ,",
        " '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'",
        " `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' "
    };

    private static final String[] TOTODILE = {
        "                          _,..----.._",
        " ,\"''-.               _.-'           `\"-._",
        ".,-.   `._          ,'    ,---.           `.             _,..",
        "||  \\     `._     ,'    .' |   .            `.     _,.-\"' _,'",
        "||   .       `-._.      |.'|   |            _...-\"'    _,'",
        "''   |           '      |  '   |         --'       _,-'",
        " \\\\  |                  '.'    |                 ,'",
        "  .`.'                   `.    '                (",
        "   `.____                  `--'                  `--..__",
        "         ``\"-.._                                        ``--..__",
        "                |\"                                              ``.",
        "                `                             .--\"''\"\"\"'`--------'",
        "                 `.                           \\",
        "     ,-\"'`-._      `-._                 `._    `.",
        "    /        `.     ,._`-.._          _,'  `-.   .",
        "   .    _      `.   |  `\"-._`     .-\"'        `-. `.",
        "   |     `\"-._   `. |--.._  `._   \\              `. .",
        "   |          `-._ `|     `-._ `-. `.              `'",
        "   `        ._    `/'         `-. `. .",
        "    \\         `\"-.'  .-....__    `. `.`.",
        "     .          /    '       `\"-.._   | \\",
        "      `.       /------\\            `  |  \\",
        "        `.___./        `              '   .",
        "             ,          `._        ,-'    |",
        "             |.-\"''\"\"'--.._`\"---'\"/       |",
        "             |  ______      `\"-../        |",
        "             .\"'      `\".       /         '",
        "           ,'            .     /         .",
        "          .              |   .'         /",
        "          |       ,'     |.-'          /",
        "          |       |      '            '",
        "           .       `-..-\"          _,'",
        "            `.                  _,\"",
        "              `._          __.-'",
        "                 `'------\"' "
    };

    private static final String[] SQUIRTLE = {
        "               _,........__",
        "            ,-'            \"`-.",
        "          ,'                   `-.",
        "        ,'                        \\",
        "      ,'                           .",
        "      .'\\               ,\"\".       `",
        "     ._.'|             / |  `       \\",
        "     |   |            `-.'  ||       `.",
        "     |   |            '-._,'||       | \\",
        "     .`.,'             `..,'.'       , |`-.",
        "     l                       .'`.  _/  |   `.",
        "     `-.._'-   ,          _ _'   -\" \\  .     `",
        "`.\"\"\"\"\"'-.`-...,---------','         `. `....__.",
        ".'        `\"-..___      __,'\\          \\  \\     \\",
        "\\_ .          |   `\"\"\"\"'    `.           . \\     \\",
        "  `.          |              `.          |  .     L",
        "    `.        |`--...________.'.        j   |     |",
        "      `._    .'      |          `.     .|   ,     |",
        "         `--,\\       .            `7\"\"' |  ,      |",
        "            ` `      `            /     |  |      |    _,-'\"\"\"`-.",
        "             \\ `.     .          /      |  '      |  ,'          `.",
        "              \\  v.__  .        '       .   \\    /| /              \\",
        "               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |",
        "                `        .        `._ ___,j.  `/ .-       ,---.     |",
        "                ,`-.      \\         .\"     `.  |/        j     `    |",
        "               /    `.     \\       /         \\ /         |     /    j",
        "              |       `-.   7-.._ .          |\"          '         /",
        "              |          `./_    `|          |            .     _,'",
        "              `.           / `----|          |-............`---'",
        "                \\          \\      |          |",
        "               ,'           )     `.         |",
        "                7____,,..--'      /          |",
        "                                  `---.__,--.'"
    };
 
    private static final String[] LAPRAS = {
        "                                       ,|",
        "                                       ||",
        "                               ,-\"'\"\"`' `._",
        "                              '----.     __`....._",
        "                               `    `.  `. ;      `.",
        "                                `.    `.  `   ,\"`. |",
        "                                  `.  _.`._   |  ' |",
        "                                  .','  ,' `.  `--'",
        "                                 /.' _,'    | /",
        "                                '/_.'       |.",
        "                                 `---`\".    ||",
        "                                       |    ||",
        "                                      ,'    `|",
        "                         _           /       |",
        "                        ' `.        .'       |",
        "                         .  `._  _,'/|       |",
        "                        _|     \"'  / |       '",
        "                    _,-' |        /  '        .",
        "                 |\"'            ,'  '          \\",
        "                 |   _        ,'   /            \\",
        "                 ;  '        /    j              .",
        "            ,\"--'    `.    .      |              |         ________",
        "            `.   -.       / '     |              |   _,-\"\"'   __.._\"`-._",
        "             ,' ,-.`-.__.' /      '              |.-'  _..--'\"       _.-'",
        "             \\.'   `-.___.'      ,               '__.-\"           _.'",
        "             /        _..--    . |              /               ,'",
        "           ,`      .-'         | |           _,'._          _,-'",
        "       _,-'      ,'           .' '       _.-'     \"-.....-\"'",
        "     ,'     __ ,'          _.'  /  __..-'",
        "   ,' _.-\"\"'  /         _.'  _.'-\"'",
        "  '-'\"       /      _.-' _.-\"",
        "            /    _.' _.-'",
        "           .   .'_.-'",
        "           | ,'.'",
        "           | .`",
        "            `"
    };

    private static final String[] MARIL = {
        "                            _,.--\"\"\"'--._",
        "                          ,\"             `.         _,.--'\"\"\"\"--.._",
        "                         /                 `.     ,\"               `.",
        "                        |  ,                 \\   '                   `.",
        "                        '.'                   \\ /                -..   .",
        "                         j                     '                    \\  |",
        "                         |                                    .._    . |",
        "                         .    .       _...         _,..._        `.  :'",
        "                          `-./      ,'    `.      /      \"`.      |  ;",
        "                             '.   ,'       |     (          \\     .-'",
        "                               `\"'         |      \\          `-..'",
        "                                          /        \\",
        "                                        ,'          \\",
        "                                     _,'             `.",
        "                                 _,-'                  \\",
        "                               ,'                       \\",
        "                              /  /\\                      \\",
        "                             /  /  \\                      \\",
        "                            /  /    \\                      l",
        "                         _,.-\"/      '--._                 |",
        "                       ,'      `.  '      `.               |",
        "                     ,' _..          _      `.             |",
        "                    ,   _  `       ,' `.      \\            |",
        "                   .  .\".`          ...        \\           '",
        "  _.--\"\"`--....--\"'|  |`' |       .(_) |        .         /",
        ",'  _              |  `../        `.__.'        |        /",
        "| ,'              ,'-\"'--._,...  ______         |    _  /",
        "|/  _.           .  .      \\_,'\"'      `-.      '     `'..__,...----._",
        "' ,'             | | \\               ,'|  \\    /                      `",
        " `|          _,-\"'.|  \\ .---,-._    /  |   | .' __                \"\"`-.\\",
        "  `.     _.-'      |  .:   j    `-.j   |  /.'--'  `.           .       |",
        "    `'\"\"'           `-''   '     ,'|   | ,'         `.          \\      |",
        "                        `-......'--...`-'             \\          .    ,'",
        "                                                       `-._      |_,.'",
        "                                                           `\"---\"' "
    };

    public static String[] getTitulo() {
        return titulo;
    }

    public static String[] getArte(String nome){
        switch (nome) {
            case "Charmander":
                return CHARMANDER;
            case "Ho-oh":
                return HO_OH;
            case "Vulpix":
                return VULPIX;
            case "Magmar": 
                return MAGMAR;
            case "Pikachu":
                return PIKACHU;
            case "Ampharos":
                return AMPHAROS;
            case "Dedenne":
                return DEDENNE;
            case "Jolteon":
                return JOLTEON;
            case "Bayleef":
                return BAYLEEF;
            case "Treecko":
                return TREECKO;
            case "Shaymin":
                return SHAYMIN;
            case "Bulbasaur":
                return BULBASAUR;
            case "Totodile":
                return TOTODILE;
            case "Squirtle":
                return SQUIRTLE;
            case "Lapras":
                return LAPRAS;
            case "Maril":
                return MARIL;
            default:
                break;
        }
        return CHARMANDER;
    }

    public static void imprimirArte(String nome){
        String[] arte = getArte(nome);
        for(int i = 0; i < arte.length; i++){
            System.out.println(arte[i]);
        }
    }

}