public class Arte {
    private static final String[] titulo = {
        "                               .::.                           ",
        "                              .;:**'                          ",
        "                              `                               ",
        "  .:XHHHHk.              db.   .;;.     dH  MX                ",
        "oMMMMMMMMMMM       ~MM  dMMP :MMMMMR   MMM  MR      ~MRMN     ",
        "QMMMMMb  'MMX       MMMMMMP !MX' :M~   MMM MMM  .oo. XMMM 'MMM",
        "  `MMMM.  )M> :X!Hk. MMMM   XMM.o'  .  MMMMMMM X?XMMM MMM>!MMP",
        "   'MMMb.dM! XM M'?M MMMMMX.`MMMMMMMM~ MM MMM XM `' MX MMXXMM ",
        "    ~MMMMM~ XMM. .XM XM`'MMMb.~*?**~ .MMX M t MMbooMM XMMMMMP ",
        "     ?MMM>  YMMMMMM! MM   `?MMRb.    `MM   !L'MMMMM XM IMMM   ",
        "      MMMX   'MMMM'  MM       ~%:           !Mh.''' dMI IMMP  ",
        "      'MMM.                                             IMX   ",
        "       ~M!M                                             IM    " 
    };

    private static final String[] CHARMANDER = {
        "                         .:::..                                                   ",
        "                     i77irrri7777Y:                                               ",
        "                  .rLi:::.:::::::iSK:                                             ",
        "                 rUi...::::::::::.:Lbi                                            ",
        "                LJ: ..:::::::::::.:i7b.                                           ",
        "               rr:..:::::::::i:i::r1ir2                                           ",
        "               Si.7:i:i::::::::L:7.YBivr                                          ",
        "               BL.ii:i:::::::i:::5  BB:2                                          ",
        "              JK i.::::::::::::..B  BQU77                                         ",
        "              UB.7.::::::::::::: BBBQgbis                                         ",
        "              LQBP.:::::::::::i:.dQMRXI:S.                                        ",
        "              7bBE.::i::::::::::.sdr2U7iuj                                        ",
        "             .7:Li.:i:i::::::::::.::::iis1                                        ",
        "             7L. ..:::::::::::.:...riYvrJv                         .i             ",
        "             u5JL:...::::.:i..::iLu:bKrid.                         rbJ.           ",
        "              u1JjuPr::::ii7sXqPXXIjJrrU7                          LJZi           ",
        "               iIjJXgPXU5SqS177i:rK5iiY2                        .7.JLLr           ",
        "                 ivJs5uUjr.. . .:U7iiru                        ir.jviuL           ",
        "                    .:rL577riiLLYrrrrLX                        i: r7L:j.          ",
        "                      .Lu77Y1Iurr7r7rvL77r:.                   L7rirv.:Pv.        ",
        "                  :rvrr:rrLsLij1U777vi:.::r77ri.               LL77r2r :uv        ",
        "              .rvjri::.7irr... .rSv::::::::::iiLLLi::u7       .7L777qL  :         ",
        "        . Y7Y7Lri.::::.JL:        7r::::::::::::::ii71L7r    .:ii r1L. .7i        ",
        "        :5Ji:::::::::.:d:          is::::::::::::.iLr7uE.   :7 . .7i   Jr7        ",
        "          :7::::::::::SX  . . ...   :1:ii.:.:::::vSE5Isi    .7i. :i   rjL.        ",
        "           LJL7JjI12Yub  . . . ...   :jiu2uILs1XjULi.         .v:: . :127         ",
        "           .:         r   . . . ...   i7.:71Y                  :1....7qS7         ",
        "                      i    . . . . .   Ji::::7                    .u7i:.          ",
        "                     :r   . . ..... .  .2.::::1                   Lrs             ",
        "                     .:    ... .....    7i:::::U.                is.Y             ",
        "                     .:     ... .....   :7::::::I.              :birJ             ",
        "                   .:uv         .. . .  .S:::::::q:            LK7ig.             ",
        "                  :7i.J.        .....::.vi..::::::q.        .rqurrXL              ",
        "                 ri.:::U.......:.:.:::.7i...:::::::b:...:rYXSI7LsJs               ",
        "                Y....:.i1.....:.:.....:J...::::::.:LB1XXKI1Lv7jUUL                ",
        "               7i .:.::rv2i. ......:...J..::::::::iiPU7L7L7Ls1uJ:                 ",
        "               u:.::rrvrrrjJr.. .......2i.::::::ii7iJI77YsusjL7.                  ",
        "               S7ir777r7rri7L2Js7r::...:Svirirr777rr7bLUYJYLi.                    ",
        "               .d77r7r7rrrrLuLJLL7i.i:rijE2r777rrr7i7brrr:.                       ",
        "               .7U77irr7rrsb              r277rrr7rr7L                            ",
        "             .rJ.11LvLu1UubL               .Xr7r7r7rrr.                           ",
        "           .j7v..v.7I7i:..                  :Irrrj7r7Dji:                         ",
        "             Lr.I:.                          vbKj.j5::JYv                         ",
        "                                               :7::Z7::J                          "
    };


    private static final String[] HO_OH = {
        "             ..                                                                   ",
        "             I7L.                                                                 ",
        "             :7::  jg:                                                            ",
        "          r7i : :i jS7                                                            ",
        "          77r:::bJ.Y1Y                                                            ",
        "         . ::  iKY7YXZ                                                            ",
        "         vs::   r7sPbP7                                                           ",
        "         .77::id77JU2bq                                                           ",
        "          :i: .UU7PKU2Mr                                                          ",
        "         iLr::  iuUb51bg.                                                         ",
        "          ir: :7::uu2J2Db                                                         ",
        "          :r7: jU775IuYXEX                        .:r1.                           ",
        "          Lrr:.:Yv2jXI2sqgU                     .i1I7q.                           ",
        "           :i:  5LYK22juJPEY                   7Ls7rirL                           ",
        "           L7r:.L7vJ5U2j1jIEL                  77L7i1I:   .:ZQb.       .Y         ",
        "           .ri:  riY1S11j1JPEY                    id1QJ:7JIBQ.        :DJ         ",
        "            .rr:.jKLIqP11jjKMq1                   LZ.2SIBQK.         sQb.Ld       ",
        "             s7r.  i71j2221qdQEU.                sqPZ2:is57r7:     iRBb .d:       ",
        "              ::r: Y2sIISU5XbbRDX:               EbUIEBD:7jr.    .MQRMduYJ        ",
        "              .Jvv. ir7jj215XbPMgbL             JMdMEM1        .bBQMBP77i         ",
        "                :ir: :LY5XUsKKPXdDMK:          i1SL          :ZBBEEbSu.vL         ",
        "                 i7J: iLLJ1qIbqbKbDMdu      .L2jd7         sBBBdbMMD::q.          ",
        "                  ..r7: .sS2XXbqPKqdMDSi..:YbIIgB       rbBQQPbbED27J7i           ",
        "                    .L7r:..UbK1dbb5KqBZ5IgZq125d    :IMBBBbbqbbDuIur7             ",
        "                      .uY:. ..IbgbZdMBQbE5IIbPBPS5ZQBBRbdbdqEbq1Lrs               ",
        "                        :5L::. ::LMBK. .iPbUqMBBBBBBgbbgbgdqIsv77.                ",
        "                           7Iii.  ::      XPbRBZMMRdMEMXIYi7uv7                   ",
        "                            .vIr7i   ...   rU1DMDMbK2Ysj7sYY:                     ",
        "                             5. .   . ...  .:iqJPjiu7sLr:.                        ",
        "                            77 .         .:r7b27su7:.                             ",
        "                            :7r     . ..::i7r...                                  ",
        "                 .rr77vuLLi rv7Lr:.7r:iriiL7                                      ",
        "              ..:XqvLYS5qPI7KQBggqPui:::r5d                                       ",
        "         ..::7J1YIr:i7j5uI172BMBDBBRU7LU1Y                                        ",
        "       .7...r7Li::vJS5bXIJjrrBBQBQL.iMBQM7:i                                      ",
        "       .ii:.:7:v7L777j7s7LYsLIjLrr   BQrDBQBg                                     ",
        "         7... .jLir7::i7UjL1qrLj2v     sBQBQB                                     ",
        "         .....:7riJjrrLuLYSd77uU2L      ..                                        ",
        "          ... .::iSjJi7Y2KI77JsLui                                                ",
        "         .ri...  .::::r2u7:i77L1u.                                                ",
        "           .   ..  .:rXirL7u7ii7r                                                 ",
        "             ::.   ::..:.r7.7:                                                    ",
        "             ii:..:.  .....:.                                                     ",
        "               :.i:::: .r.:                                                       ",
        "                  ...   .                                                         "   
    };    

    private static final String[] VULPIX = {
        "                     iLYL7i:                                                      ",
        "               :1JsP177iiirv1L.                                                   ",
        "   .          :Pv7Ji::::i7LJ721r:                                                 ",
        "   qBis7i.    b77Ju.i::rui::::iiYJ:                                               ",
        "   uBU:vUKY:  PXLPU:ir7X:iiiiL7sr7b:                                              ",
        "   7BBriri2bqiL77L17viUriii7UsvIdrIY                                              ",
        "   :QBM:iqLrir::...:rsPviriSrJvUs72i               .irr7ir..                      ",
        "    BZBUbu:.::i:::rir:r77vjEJj1JJLE.            :Y1YL77rsY1Uj:                    ",
        "    qKUBu.iLi7:rvYv7777uuuLLri::...:7Yu51Yr:  iSLr:i:i::irirLbqrrLLLi:            ",
        "    .MIBii1rii1bX2uuu5S7rii:i:::7LSdQQBQBBBr 7X:::i:i:::irJJLi7rriiiY2Ir          ",
        "     rbvLUr7U55urriii7irrr::iUEBBBQBMRZMBM  Xs.::::::iirvs7:.::i:i:rrrrj5r        ",
        "     :L.KPJKJi:.:iL77iirrr5BBBBMQMRDZbBBv rZS:::iir:77i1Y:::i:i:::rr7iri7jI       ",
        "     1ii:S5i:::r:LBMZd7ri1DbJuIQMbIUJMM  2LPi::rrrrLJi1s.::iii:i:777rrrrrruI      ",
        "  ir7:iii:i:iiug iBqX5Zi7i::rYZSYLUqK:  E7IXii7r7ii27L1:::ri7iiij1vr7r7r7rrP:     ",
        "rQQBBrr7r7r7rrdBZqL7:5Prr7rrLM2Y5D5: .LRLv2q:rr7rr:jjK:r:7rrr7iJ5iiririririur     ",
        "X1QRji7777777rrL277rvJrr7r7rvdXRJ   YIUIL7YE::ririi:S5:i7r7r7irb:ivLLYjjUJY1:     ",
        " 77:irr7r7r777ri:rrv7rr7r7r7r7vg   iSrjS7L75Si:iiri:vX:rr7r7rriDs17r:i::ir7Sr     ",
        "  UI77Lrir7r7rrr7r7r7r777r7r7rq:   Pu7Jq7vL75b7:rrr:LP:r7rrriiU27:::::::::::LIr   ",
        "   vXjjEu7r7r7r7777777r7r777rXi    bIJ75177L7ubIi7rriEirr7iirb7i:iirir:iirrrr7Iu  ",
        "    .JU7bUL7777777777r7r7r7r2:     :QJLLbXL7L7v5Kr7riXLi7rirE7iirr7r7i7ri:rrrrru2 ",
        "      7K2ILLvL7v7L777v77r777J       :EK2L2XSL77v1brriIui7r7giirrrrii7uLLYJ7iirirI:",
        "       .r7U2Is77v77777777r77L1r.      .rUI5bMqUY7XSrrXJr7vbriirrrrrYjr7r77IYiirr7U",
        "            .iXY777777r7r7r777j2js77i7:ir7i::7sK1buvubi715iiiririr7Xi77777iPrirv7s",
        "              IUsLL7777r7r7r7r77vvsLJLL77irii:iiLqXs1ivSjirir7YYuv5Ev7rr777K7rv77L",
        "              77rr7JLv77r7r7r7r7r7r7r777r7r777r7iivqLjY7i7YUujLL7777LU1Yir777v777U",
        "              S. ..:YY7r7r7r77777r7r777r7r7r777r7rrrb77LU1s7r:::i:iii:rLX7rr7777R.",
        "              K. .   rL777r7r7r7r7r7r7r7r7r7r777r7rrrE7L7ri777rr77rrr7ri7P7777sM7 ",
        "              uK  .   rv77777r7r7r7r777r7r7r7r777r7ri2s777777rujuuIjLi77r7q7jPX.  ",
        "               Bi  .  .ur777r7r777r7r777r7r7r777r7r7i22LS5L7rqY7r7775Jr77rPbL.    ",
        "               1ML..:.:u7r7r7r7r7r7rv7L7Jr7r7r7r7r7r71  .iU1P1ir7r7ivIr7vrE       ",
        "                DP2r:::U77r7r7r7r77vir::s7r7r7r7r777rP     .bS7L7777Jsr7rqY       ",
        "                :dJ5J:.iji7r7r7r7ru7.::.7Lrr7r777r7rvI       Ybv7777v7vvKP        ",
        "                 LqvUXsiJrr7r7r7r7Ii:i:.ib:rr7r7r7rrYL        :155u1j5SPr         ",
        "                  PuYvUuZUir7r7r7rK77:7PSKbrir7r7r7i7q          .:rr7i:           ",
        "                  .bi7rrLPirr7r77sY   7bYY2bXus777r77SD                           ",
        "                   UYii:rP7r7irirX:   gusYjbY r5sLLvYLDi                          ",
        "                   LbuYjLB11YLLv7R   sRP2juD   71LLsvLE.                          ",
        "                   rZjUuJbIJU15UD7  LEujSSBi   v57v7LjE                           ",
        "                   X22JsJbY1jujKM  BQj2U1BE    bXILL7Mi                           ",
        "                 7BJL7s5b1jjUj1R7  LBMBbEY    sP21IUKP                            ",
        "                 7BMBbMXvir7YSMU            SR17LvJdB.                            ",
        "                    ..PQQKRqZQ7             dQDQRPQM.                             ",
        "                       .i7rY7.                :7rr:                               "
    };

    private static final String[] MAGMAR = {
        "                                                                 i:                          ",
        "                                                                :.:.                         ",
        "                                           7:.L.           .i::7. ::                         ",
        "                                           .::::.:i         :... .7                          ",
        "                                             .:...i         i ....:ri.                       ",
        "                                              :....:.:::.: .7:.... ..ir                      ",
        "                                             :: .........i.  :7.......i                      ",
        "                                             i::.. ......r   ::.....:.                       ",
        "                                          .   ..:i. . ...:  :.  . .::                        ",
        "                                          72      r :.    ..::.    .. :r:                    ",
        "                                          .QJ     7i.J7:r::7YjUJLi::7rvUKKL                  ",
        "                                           1S2   ..IirjuYUYLvLvssIKuLJLLi:17                 ",
        "                                 7.        :5sI  uY7jvL7L7L7v7Lr::7uv7v7rivK                 ",
        "   :                             YRL.       SJub  jv7v7v777v7v77::rj7v7v77j7           .     ",
        "   :r.:                           sdXs:     PKKPd1Sv77v7v7Y7L7L7v7sjjsuLvJU:uLLYX: .7:..  .  ",
        "  .r r                             jIjU2r   sR52UbbELL777Yi1jUsJjXXL:i:r217Y11uYL2XSj2ss. :  ",
        "  L..:.::                           u1vUgZL.:.    .:L1J7vs.    uKr::   ru777JsL7I7LUsi:rq7 .:",
        " .7. ..:r                            uKSID7.         .LJ7vsr:iuY     iu1LL77rUr7uYrL57rLIZ . ",
        "  .i  :i                  :           bqb:    .   .    v777ir:.     . . :UYr71ur7sY5S1qS::.  ",
        "   i ibU:.                1Mj7.        Q1   .71L rIsi  iKr::..  .riJ7r.:LX777LLL7IbX .:. .ri ",
        "  i ..7Y25b:               iDK5us7:    .u  :ruYjLLsLX: 7BBMdMQBU.7u2i.  7IX52S5SX7.          ",
        "  : 7L.L7LX:                 1XSKdEEI7. U :KL77sL777s1rSQBBBBBQBB7:i.. .Sb7.r...             ",
        " :I. vu7v71i                  .Kg5215PDbXi7LLJY7sLsJsLuLr7IPMZdIui   .:7.                    ",
        "  Ei .iY7v7Z7                   :Xq1U5uU7L7YvLLv7L77777Lrr:i:iiir2i..::                      ",
        " .Esssv7v7ui                      .UKY17777YL777LvLLL7u7Us77vr:::is                          ",
        " :bqSX5uLsJ            .PZKUUbSIj7.U1Uj77777Jv7J77LLrr7LrjJ7vi::::7:                         ",
        "      .7bS2u:            :jSgbKSXIbbjI2r77v7LLsLLr77LLJYsL1LYi:iii77                         ",
        "        .:JSqK:             rbZK12X7ibSsssv7LL77r7JUJsv7711:7Y7: 7Y5                         ",
        "           vi7b2:             :1dPd::ivi77u157vrYUL7777::7X. i57 .EJ                         ",
        "            .  i::::            .U:        :LXJLU77v7uuj7:YPvLuZ. :7 :                       ",
        "             :. . .:i::.        .   .....    :XUXLJs1..SL  rJ1i   i...r                      ",
        "              :: ... ..:::::.. i.........     .IiL :E. i:. :s5r  ::.   7                     ",
        "               :r.............s: ............. : : .::.. rb7sYj .i.... 7.                    ",
        "                 r:. .........Li ............. :..::  .:. i2XL .:. ... s                     ",
        "                  .i:........ Li: ............ i. :......  :7.... ... :L                     ",
        "                    .r:...... :L:: ........... J.    ... .   ..  . . :s                      ",
        "                      .:i:...  rL::   . ...   vLri:...:::::.       .ri                       ",
        "                         .::::. :ii.       .:7rr7J5Ii:..   .QKJ7rEB.                         ",
        "                            .... rBQ57r:r:rLJ77ii..        jBBBdKBB                          ",
        "                                 BQBIqQBB  .             1JXBBBX2BBLv7i:.                    ",
        "                                bBBq7bBQi               YKLr7sXJjL77sJ2IqSPi                 ",
        "                              r2XBBJjBBB                :ZsLriirirr77LYJLj:L:                ",
        "                             iK7rYP1ZRUrv                :IIS2UYY7v7Lvr75K   ..              ",
        "                            :Pvv7ririii7S.                  .:iY15Jss7   7bL..::             ",
        "                           .dYL7777777v7K:                       .L1Kbr   7:  ..             ",
        "                           E5jjL777vYUuJ2L                           .......                 ",
        "                          :Z  .Uv7Ls7  sbu                                                   ",
        "                           :  :EJuJb.  iE.                                                   ",
        "                          .. .7rv7sY:  i                                                     ",
        "                           i        . .                                                      "
    };

    private static final String[] PIKACHU = {
        "                      Mr                                                                    ",
        "                      sBBgL.                                                                ",
        "                       EBBBBBq:.                                                            ",
        "                        bBQBB:.iri                                                          ",
        "                         jBBB ...:7r.                                                    .v7",
        "                          iBB .....:7v.                                           ..:RBBBBB7",
        "                           .B:........77.                                      .irr:.BBBBBr ",
        "                             7i........:7r                                  .rri:... MBBQ.  ",
        "                              ivi........:L.                             .77i....... BBZ    ",
        "                                rL:........Yi    .........             i7r:.........rBi     ",
        "            .                    .7Li.......L7:irrriiiiiri7r7ri.     iLi..........:ir       ",
        "          .virii.                  .rYi:.....i.:.............::r7r.ivi..........i7:         ",
        "         i7....:ir7:.                 i7ri........................i7.........:rr:           ",
        "        7i.........:i7i:                iL.............:.................:i7ri.             ",
        "       7:.............:i7r:             v.... ........................Yv7i:                 ",
        "      L:.......:.........::77i         7:..  :Lr.......:.:............r7                    ",
        "    .L:.............:.......::ri:      J.. .BBr 7i......:...... ..  ...v                    ",
        "   .L:...:.....................::ri:  .L.. MBBr BB ............r:Ld: ..J                    ",
        "   Y:..............................:r:J..  :BBBBBi........... BQ  BBi .L                    ",
        "  v:.........................:7i7i.. :i ..   7s7  .....7:.... BBBBBB7 .7                    ",
        " ::........................:Uir:iv:  rv2K5Xv    ...    .  . . .ZBQBv ..7                    ",
        "i7irii:::::::::::::i:i:i::iI......r7rgIuYJJb2.....bMPMBBU:.:..         7                    ",
        "   ..:r7YYJsY77iriiiiirii:rY........7MXssLuSP.... DBBQQBBBBQ:.... .7Yvir                    ",
        "           ::r7LLYvvrr:i:i:Yi....... .7PI5XX..... vMI52SSEBJ ... rdK2SSB.                   ",
        "                 .::r7YLs77i2......... :Sr: ..... iS7r77LqS .....d5YJY1Q.                   ",
        "                        .::iYJ ..........r........ 1iiii7j...... Jb5jSDr                    ",
        "                             iY ..........7r.......:XLYuL........ iYbP.                     ",
        "                            .Lsr ..........7r........7r: ..........:.                       ",
        "                           :j::Yr ..........7:....... ..........iui                         ",
        "                          7u:i::LL...........:...:::.........::r::r                         ",
        "                         LY:i::irii:..............ir7ir::.........7.                        ",
        "                       .Uv:i:i:77  .:...............::.....:......:7                        ",
        "                       YSvvri:i:i77.Uui...................ir.......v                        ",
        "                         .:7vY7r:::7uis7.........:........L....:...L                        ",
        "                              ..L::L:....................ri........Y.                       ",
        "                               :r::j...........:...:.....Y.........u                        ",
        "                              PQSLui..............:.....:7....:....Y                        ",
        "                            iBBZgdL.....................ir...:....:v                        ",
        "                            IBBQMBi ..iLKss::.......:...ri....... Y7r.  ..                  ",
        "                               LMM ..i.777i7.7i.........ir.......rr..rri1Q.                 ",
        "                                 L.....i:i:i: ii..:.:...77......:7...:LiUZ                  ",
        "                                .7.....ii:::v............i7rii:is...:7.iJJ                  ",
        "                                .7......1:i:si........... ..::i::..:Y:i:5                   ",
        "                                 U.....:1r:::5::...::iii::::.. ....7ii:u:                   ",
        "                                 :j:::r:7Y:::Y7:iiririiiriririi:::iii:sr                    ",
        "                                  :2Y7ii:1i::v7:iriiiiiiiiii:iiririi:J7                     ",
        "                                    :rYv7LP::7S7L7LLY7LvLvL7v77rvs:iui                      ",
        "                                           i:7                   7::                        "
    };

    private static final String[] AMPHAROS = {
        "                                   .vr.                                          ", 
        "                                  .S77J7                                         ", 
        "                                  U. :QBB:    :.rJJPP                            ", 
        "                                  :MQQQBB1..:S7 YBBBQ.                           ", 
        "                                   M:.25  ..Db  rQBBD                            ", 
        "                                   5UjuL....UBQi..:i                             ",
        "                                  :vUr. . ...XBQBEr                              ",
        "                                 i... .LQ1 .  .iii                               ",  
        "                                .:....:BBs..:.. r.                               ", 
        "                                ::::.:.....:...77                                ", 
        "                                7::::::.....::7u                                 ", 
        "                                :7:::::iisL7777J                                 ", 
        "                                 .:::::::.rvriii                                 ", 
        "                                           i.::X:                                ", 
        "                                           :7UMQI                                ", 
        "                                           .r2bDQ                                ", 
        "                                           :2bZbBi                               ", 
        "                                           r7dgQKr                               ", 
        "                                          .: ..  7:                              ", 
        "                                          :.i:    7:                             ", 
        "                ::              ..:::::iii::i      IILYv7::..                    ", 
        "              2YYMZ.       ..::i:::::::..ii7       .SsLvi::iii::..               ", 
        "              PQM1P.     .::i.........:i7i7.        ::7J7::...:::::.             ", 
        "               :B2      7r:......::::7r:.i:          :  .::iiriii::7:            ", 
        "                BR      ..:::::::.. ::..i:           .:       ... .              ", 
        "                UBi                .:..:r             r.                         ", 
        "                :i7i              :i:.:7              :v                         ", 
        "                 gBB:            :r:.:r.              :Yi                        ", 
        "                 .B iS7         .s:.:r               .i:Pi                       ", 
        "                   bQBBBL.     ii..::r               ::.s5:                      ", 
        "                   YBBr .::i:iL......:i             :::.s7J                      ", 
        "                    UB.:::...7.....:.:r           .:::..s77r                     ", 
        "                     :17rir:v: ...:::.7         .:::::.isi7Y                     ", 
        "                       7JYrr2. ..:.:..r.  ...::::::::..uirrU                     ", 
        "                        .vUYU..::.....r:iiiii::::.:...LrriJ7                     ", 
        "                          .Lb:.......:i..:::.:.:.:::is7iiYs                      ", 
        "                            .ji::.:.iLi::::::ir7sIKPD5JLI7                       ", 
        "                             s777YLUEbSX22uu1KKq27:r1S1XK                        ", 
        "                            :Y77uv.  .:irrriri:     iE2UPur..                    ", 
        "                           :uvrY:                   .MD177iiii:                  ", 
        "                         .YLrrYi                      7Jj:::.:rs                 ", 
        "                        ::.. .:r                        ..:::L::                 ", 
        "                       rr .....7.                                                ", 
        "                        i77iiuir                                                 ", 
        "                          . ..                                                   "   
    };

    private static final String[] DEDENNE = {
        "                        .7jIu1r:                            .::i.                 ",
        "                      UKIsYLKEBBMs.                      7bQBQMEdPbY.             ",
        "                    rBJ::i::  .iZBQI                   :MgRb7::::iijZP            ",
        "                   iB7::.        dBBE                 :QbQ7     ..:::5B.          ",
        "                   QE:.           QBQr                BBBP          ..bB          ",
        "                  LDb         .   7QBd               7BMB             UBI         ",
        "                  UZd    . . .    .BQQ               ZQQM             2BK         ",
        "                  rBBL    .   .   .QBb               BMMQ   .         BQj         ",
        "                   QQB7           7BB7  ....::...    MQRQ            MQB          ",
        "                    ZQBM:         BBBr.i7rririrrri7i.dBMB          .BBBr          ",
        "                     iQBQBY.  .. XBBD..:.:::::::::::.iBQBI .     :EBBBi           ",
        "                       :ZBBBBQRISBBB:.:::::::::::.:.. IBBBu:77YdBBBBJ             ",
        "                  .       .7QBQBQBg. ..:.:.:.:.:.:.::i.bBBBBBBQBBj.    v          ",
        "                 Ug         i.::r:..:.:::.:.:.:.:.::ii:.YqdKu2L        bB    .    ",
        "           :Xi  IB        L7::::.::iii:::iii:i:i:iirir::......i:    r   MM.UQv    ",
        "            :qMPB.  b    sviiii:i:iviriiriririririii7iY:::::::iJi   IR  XgB1      ",
        "              ZMKKYBr   7v:.:::i:7B  7X:iiiiiiiiii:d  LB.:::::::s.   BDgurBj      ",
        "             KB. JBQBJ  7.:r7i:::DBjvQR.iiiii:i:i::BX:bBj.:iv7:.:J7BBbPB  .Bj     ",
        "            iB.  B7 7BQBL:rii7jr.EBQQBL.:i::7r:i::.DQBdBI.7u77L7XBQBi  qb   7     ",
        "            .    .    :RBBPi:rYU::KSqY.:::iii:i:::::SXKU:iIi7jRQZSr               ",
        "                       :.KBBDYiuL.:i::rLsuK7 :XIYYr:.ii:.U7LBBBRi7                ",
        "                     .iMQMBXPv7L1:::::iiqj77777vKLiii:::iU7rLJbDQBBBD1r.          ",
        "                .vXBBBZ72i7vir7jL::iii:::ririrrLi::iii:i:577irL::: iLPbgZE1.      ",
        "              :Kb2r.    r.:vuLjji:i:i:i:i:iirii:::i:iiii:72sJLi.r:        .       ",
        "                       uii:::ri::i:i:i:i:i:i:iiiiiiiii:i::i7:::i:LY               ",
        "                      J7i:i:::::iii:i:i:iirr7rrii:i:iiiiiii:iiiii:jr              ",
        "                     :Liiiiiiiii:iiri77ii:..  .::::si::::iii:iiiiiiK              ",
        "       7E:           77iiiiii:iii:::::77riirriiirYrr..:.::iiiiiiiii7.             ",
        "       EDZbr .s:     sii:i:iii::::.:...:vBBBQBQBQB:..:...::::iiiii:7              ",
        "       552SqbPB      Yi:i:iii::ir.:.::i:K:.   ...uUi1:irsb7..:::::iLBMBQBQDs.     ",
        "     .:bdgdUubR77    J17i:::::iKDBsv7I7::           :JrjBBBgsi.:i7rqBBBBBBBBBB    ",
        "    1BBMQEZbDERBB    .MJJ7r:rJbMMi  :i                   :ZBBBZUsrvi      :BBBs   ",
        "     .:uRBRBgQBu      7b777XbMM1.      . . . . ........:...iuBQBBMQL..::rUQBQD    ",
        "        QBBBBBB        :u2QQBq:.:iririririririiiriiiiii:i::. .5bBBBQBQBBBQBP:     ",
        "        ..  :BBBZi.   .vBBBRL .::i:i:i:i:i:i:i:i:i:i:i::::::..5I:  ..::.          ",
        "              7QBBBBBBBQQi.:Sr:.::::::i:i:::i:i:i::::::::.::rLr                   ",
        "                 :7Jsv:    UbE5L7r:iiiii:i:i:i:::i:iiii7rLJ5Mi                    ",
        "                          5UiYE51PgMi:ririi:::::i:irrgK2DdELLPi                   ",
        "                              :   .:                     ..                       "
    };

    private static final String[] JOLTEON = {
        "                                    .ii                                  ",
        "                                 ... j                                   ",
        "                            .:ii::..U.                                   ",
        "                         :i7i:...:iu.                                    ",
        "                      :rs7r:::i::r7                                      ",
        "                   .iJ7r:::i:i:i71r             ..i:                     ",
        "                  7J7:::::i:i:::Y7      . ..:7r:ivJ.                     ",
        "                .ji::i:::::::i:7i   .::7sXDBQj.ir.                       ",
        "               i1:i:Ii::::r:.  ..iubBBBBBBBB: r:                         ",
        "              rXr7:77:.ir:  :IRBBBBBBBQBBR. .:                           ",
        "             Ybr: :1Uir. .5BBBBBMZZdBQBM: ..                             ",
        "         ...L2.  . i2r vBBBBMgEggQQBBg:  77..                            ",
        "      .r:.... .....i::bQBBBBBBBQBQgJ.  .i:ii:                            ",
        "     .v.   . . .....:vr5QZ2Jrr::.....::.                                 ",
        "    :7...  .. ........::   .:                                            ",
        "  :::. . i7 MBQB ....::i:LL:.                :.                          ",
        ":1s   . iQBBBBB: ..:i::::.i7  .::  ...:::.:rv7.      7                   ",
        ".r:. .....ijLL. .::i::::::.i7Y:Li:::..  .:i:       i5U         .Yr.r     ",
        "  7J:.         .:::::::::7Y:7J:       .:i:     j::77s      .::rrYr5:     ",
        "   jJ7ri:i:.::::::::::.:::v1..::...::isvr:   :vPri.1    .ii:.. .::       ",
        "    7Jvrr:i:i::::::.ir577i7Kj.:.:.... .i:..:Xv::..7i .iri.....i:         ",
        "      :ii7i:::::..:.rUr:.....:.. .       ...::iLJrSi::.. ...:r           ",
        "        .i:u::::175irS....:.::.  .::::i::ii.:...:.. . ....iL:    .....:r:",
        "     :77:  r1v77L::.:r::::::....  ru7........... . .....:iYr.:::::.::7r: ",
        "     :.  iu.i..rb.......:.::. ... .i. ....................  . ...:i::    ",
        "         7.. .:...::::.:.:..   ..7:.vi.......................:::..       ",
        "       :u.7.  .:. . .::... r:     7r.:.....................7U:           ",
        "       . i.  :.  .   ..:.  :L::.   :i .......................:::..       ",
        "        ::  :I: .  .    .   :..ir:. .r.....................i:.::i7j.     ",
        "       .i  :js7  . 17 i:    Ls...:ii.i7.:i.................v7.           ",
        "       7 .7 .vL    v::Lir.  :7......:.77..::L2YLi:... ..... .:.          ",
        "      ::::  .L7:  .r :J..ri  r........      .riiirr7r7::.  . 7ri.        ",
        "      S:.    UiJ  ::......:i:.7 ...:ii7rLrv.  ..::::i::irLi:.:b:         ",
        "      .      Yis. u: .......i7SLrJY7::. rKYU:  .....:... v .::7U         ",
        "             .j:L Zi ......uL:i:.        7YrIi  .........:      .        ",
        "              J::sj7 .... 7:              I7iIr ........ r.              ",
        "              r7:ir7......j               .j7iI7  .......:J              ",
        "               s:::s ... Y.                Jr7iusi.. ....:s.             ",
        "               7:::j....:7                rLrrr7q1i77::::::Y.            ",
        "               7...J ...r:               JUrrrLK:   .7Lr.:::j7           ",
        "               r: :7..:.v               usii7uY        .s.:::2:          ",
        "               Y. ri ..:7           ..iX7iiY1:         :Y::::1           ",
        "              .7..Y....ii          KZJYr7v5r          .J::::1.           ",
        "              i: :r... j           :YbLL77.           j::::s.            ",
        "             .i..L:...:L                           .:vr::is.             ",
        "            7J .ii ...L:                         :1i:::irs               ",
        "            iI757 ...ir                          :Qi5i7i:                ",
        "               .7:v:.                              ...                   "
    };

    private static final String[] BAYLEEF = {
        "                                            .7:                                  ", 
        "                                         i7bQ5                                   ", 
        "                                     .LKZKbBi                                    ", 
        "                                   7LIuLi7B7                                     ", 
        "                                .vjr:::.:Ed                                      ", 
        "                              :L7i:sI5srJQ                                       ", 
        "                            .sji:LBj: .bQ.                                       ", 
        "                           r1r::JB    .B.                                        ", 
        "                          Y7i:i:d     .                                          ", 
        "                        .Ui::::::rsP:                                            ", 
        "                       .Drii777LUjr                                              ", 
        "                      .EUPPd55L7:.                                               ", 
        "                      gbbL::..  ..iir.                                           ", 
        "                     PQr  i:       ..r7                                          ", 
        "                    sM  .XBZ .. u5. . 5Y                                         ", 
        "                   :BB1QBBB: .rUBBr. .7B                                         ", 
        "                   :MuiLIR: . .BBB.. 71Mi                                        ", 
        "                       :.  . . BBQ .rIsMi                                        ", 
        "                       .j.  .   ..7Lv7sg.                                        ", 
        "                        .LLSuqSIL2s7vujZ                                         ", 
        "                          ..i77JBDP15jLL                                         ", 
        "                               .qsLY7: :  UggB                                   ", 
        "                               i:....  7XQBQBX                                   ", 
        "                       MZQEu:  r . ... BQBBBD7Pgs21X                             ", 
        "                      LBQBBBBP: ..... BB7s:.rI:jDB7                              ", 
        "                        .BBBQBQ. .... .QsrKY7MEb2v                               ", 
        "                           .Lbq .....  JSiYJ7i.               .                  ", 
        "                        ::r:.r  ...  .ULv7r: ..::.         .::Ii                 ", 
        "                    .vKQBQBRBB.i. .7: Dq:Y5Y77i..:iii.. :ruSr.P.                 ", 
        "                   UBgBBRBQBPsrBr 1jjY.YQ2:.i7ju:  ..rbBRDXS5B:                  ", 
        "                   .ri77.:7L7 UB. P:iiX. LQBb7i:j5...  rBKIUR1                   ", 
        "                         L  rSBi  D7iriE:  iJZMMMD.... .sRuRb                    ", 
        "                        Ls7.PB  . J2..::g.      . .....rrUB7                     ", 
        "                       Ii:BBBs.    DZrriBs ...........:rLLE                      ", 
        "                      .BBBMjuL2Li:..MQKvBu ........ .:r7sJSL                     ", 
        "                       uj: .KsL1suLrr2MBB: ........:i77JLvLb                     ", 
        "                           .XLjLuYIPIJsu. ........DJYLJYL77E.                    ", 
        "                           :qLLsLL7jDYr2d ...... .M55ILL777K.                    ", 
        "                           .g7YLJLssq   v:...... iK7DLsLL775:                    ", 
        "                            buLjj1Ygr    L ....  M: LqsJL7id.                    ", 
        "                            L7i:rv2M     QU    .7Q:  2qIULLZ                     ", 
        "                           .L.:: :qi     :QJiiisuB    7DbBQi                     ", 
        "                           7J:K1:::       7KLYI1qQ       .                       ", 
        "                                          7S:isSv.                               ", 
        "                                            ...                                  " 
    };

    private static final String[] TREECKO = {
        "                              .::.                                                ",
        "                      ..     .7ii77i                                              ",
        "                    .Lri7ri.r7  ...is.                                            ",
        "                    U....rLq5 ...:...u:                                           ",
        "                   rr....iru:...:.....j:                                          ",
        "                   u.....:7K.......... Y.                                         ",
        "                   v:.....i2........::i:L                                         ",
        "                   r...:..:J ....rLsM:.7K7                                        ",
        "                   Si...:.:Y....jY. 1q  LI                                        ",
        "                   Sr......U.. J7    B. :vr                                       ",
        "                  .:r......r:..X:    QJ :iJ                                       ",
        "                   s:7..........j: . LJ iJY7                                      ",
        "                   .Ys:.:.......:si.. . s77J                ..                    ",
        "          ..        :J...:.:.:....rr:..r7iLJ              7:.:L                   ",
        "        .ii7r.::    .i..:.:....... .:i7jiib            ..7rr.:Y                   ",
        "       irJ:..Uir1   :Y ..:..........:7PS:Kr          :j..d7I7i::::                ",
        "     .5:::ir..L:7    1:...::...:2uI2SUP:LL           uui:J7v7r5:.j.               ",
        "      :ri:.r...ir     rr .:: .:2bLssvKir7   ..:iiiir:77YU7rrrb:r7r                ",
        "         ri ....ir7::.:Lsi::77Y5YjYLS7iS::rri::::.... .i77LYbr                    ",
        "          LL:......:::..iYu2jIri5bLJ2:.......::i:ii777rri77i.                     ",
        "           .iiv77rriii::::rv7risr::::v. .:iiri:..                                 ",
        "                 . ..:.:i77s77Ur.::::ij.:5.                                       ",
        "                             .Y:i:i:i:72 .v                                       ",
        "                             J:i:i:i:::P: r7                                      ",
        "                            7Li:i:i:i:ivY .I                                      ",
        "                            X:.i:i:i::ir2. 7L                                     ",
        "                           :X..:i:i::iriI..iK                                     ",
        "                           :I::i:::::rirs :su                                     ",
        "                            Dii:::ii7irU7.7L7                                     ",
        "                            rBLYLJYJLYuMiriXi..:....                              ",
        "                             JQLvr7r7YE7iiYUL7LLsLYL2uYrr.                        ",
        "                              SUjL7Jsuriiuuiiiii:iiiii:irLs7:                     ",
        "                             .IiiYE21:irrjX:::iiiiiiii:.:.::Ls7.     :ri7:        ",
        "                             Lri:MdUqd:ri:dY:::iiiiiiiii::::.:ijLi  vL:i7s5:      ",
        "                            .Y..i7S12Z7 . LB2i::i:iiiiiiiiriiii:ivsrP.iii:iK.     ",
        "                            1:..L .gUPX .. QMS7r:::iiiiiiriiiriiii:7IYi:iv7II     ",
        "                          .r7...X  7MSQi . rRqbUsri:::iiiiiiiiiiiii::7Ui77L2j     ",
        "                  ..   .:iii....u:  :dQI .. XPIbXIY7i::::iii:iiiiiii::iLi77Z.     ",
        "                i7.:YLs.::.......v    57 .. .gqjXSqU1YLri:::::::i:i:i::::7bi      ",
        "                7u:L. .i.::v....7L    :. ... .DESIUbPPSS5Uv7ii:::::::i:L15:       ",
        "                 rXd7i7b...r:.71s  ..7v  .:.. r1LqEdRQBdbMMMDdd55IKSbbE1:         ",
        "                   .irrKUsLsJ17.  ii.::.:::i::.  .j..     .ir77sj1Lv:.            ",
        "                         .::.     I7:.:sS ..:Yriirr                               ",
        "                                   j7Lr:LULsL:rLv:                                ",
        "                                          .                                       "
    };

    private static final String[] SHAYMIN = {
        "                            .Ls7777:.        ::                                   ",
        "                            :1.:::i7sj:     7sv1                                  ",
        "                             77.:::.:i157   1::i5                                 ",
        "                .::i:iii:.    rr.:.::::iLUi v:..72   :                            ",
        "                biiiiir7uJJL7. 7s:iiiiriiivSg:iiiji jXr                           ",
        "                 7i:.::::iirrL77bj7iiiiiii:irririi71777    ..                     ",
        "            ..::..1Si:rirrriiii::iLriiiiriiiiiiii:jd:ir :vjLS                     ",
        "       .i77L7YLsL7r7iririiiririiii:iiiiriiii:iiiiirj:LP7rii5:.:i::..              ",
        "      .q7:..:.::iiiiiiriiiriiirii:i:iiiii:ii7ri:i::::Lr:i7JJrvL7v7sjjs:           ",
        "       :rLi7:i:i:iiiiiii:iiriiii:7U7:i:i:rYr::sL:i:i:i:iiriiiiii:::7Lgi           ",
        "         .LIL7vYuiiir:ir7ir:i::iu7:27:i:i:7777vi:iiiiirii:iiiiiiLIYi:             ",
        "       :ri.....:ii:i:77:.iu:::iJ:..:JL:i:i:i:i:iiriiiriiiririii7LUriiri:          ",
        "      L7:.::::::i:i::J:.rvr::7s.::::.sU:iiiiiiririiiiiriiiriiii:::iirrvLjr:       ",
        "     Ji:.:.::::::i:i:irv7i:iiS.::::::.jJ:i:ririiii:::iiiii:i:iiiii:iiiiii77Y7:    ",
        "     u:.:.::::iiiiiii:i:i:i:S7.::::::::Si7uLjYv7777vr:i:ii7r7iiiiirii:::ii7vE2    ",
        "     rUi:::iiiiiii:i:iirii::Ir:i:i:i::.bd7i:.:.:::.Xri:i:Y7..7iiiiii:7SKrr::.     ",
        "      .J577rr:iiirL7Yj1LjsY7Piiiririi::Pr.:::::::.iY:s2:i:LviL7:i:iii:LuYi.       ",
        "       rri7LLjYLJEri::.:::ir55irir:iiirJ:::ii:::..j:.::::::irr:iiiiii77v7j157.    ",
        "       L:.:.::...7:.::::::::i7rii:Iviii:iiriri:..uKrYLLL7i::..::iiii77v7777LIKU.  ",
        "      si.:....ri  L::::::i:ii::ii:MM:i:rjiiri:..LMSqXPqdqdbSYYi::ii77777r77v7LYqr ",
        "    :s:      .rM  iU:.:::iriiuJiiirii:LBX:i:iivIbuUu11Uj21SXbdEULir7v77JSv7r7777Sr",
        " ..ii        RBB   ij7::iiiii1MU:i:iiii::i:7uEMgS5U21UuUj2u1juj5bM2rr77vvU1j7j15Iq",
        "BB7          DBq     7s77ii:i:::iirii:i:::iii::rIEqJ212uUj1JUuIUIIgdLr777rvXd::ri ",
        "bB7          :I.       :RSiii::riiii:i:qBI:ri:::.iPXjujU121IU5UUJuYSgurLLL77uY    ",
        " r                    7vr:iiiLBj:iiriirir7rri:::..:b5uUuIuI11JuYJvYvYbUrv7L77jb.  ",
        "  r.                 5Ji:irr:Yv:ir:RR:irr::iii::::.7bU121UuIujLY7v7L77qur77v7vYb  ",
        "   7i ::i::i1Z7     rK:.::iir:ir7iiLX:riYs:::::.:...b2IUI1I2Iss7L7L7L77PjsL777Luu ",
        "    .7:.:RQRPbgJ    7j.::::iiii2rrii:iii:UK7::...::.jEj512UIu1sY7L7L7vrLKYuIJJvUb ",
        "      .:. 7PgZrUr   77::::::::1giiiirii::iBMMdZbBDDdEPU1UuU151uLL7v7YYUuq5rJ5:uUv ",
        "         ..:LXs1S...7Y.::::i7Ii1r:::::::.:MPXbPdbdED5dbP2S5XIqXPSqXXuuLL77ruv     ",
        "             .r7Yri.iI:i77Y7r..:Ki.:::::.rQ5X5qSKSKRL.5bEbEXS2IsY77rrirr77Yb:     ",
        "                 ::v.J7ri:...::.ibL:.::..bbKSqKKSqIXQ.  .irLvL77r7777v7LYXSi      ",
        "                   LL.....::::::..LjL:. 1QP5X5K5X5SUB7 .. ..:i7L21UJU51bb.        ",
        "                   iui::::.:::::.:..:BK7gK25IX5SIS2XZS ..:...........:ir          ",
        "                   .d:rir7P7..:::::. SBZPU5IXI52SUSSgX .:::.:.:... .ii.           ",
        "                    sr:i::52 :.:.:.. .EMKqXK5SI5252SdX ..:.:.....:7b.             ",
        "                    .2::i.d7..:.:....7YIQQMbqSXSK55UZs  ....:.:::7Z:              ",
        "                     2::::5..:.:.:.:ji ..71bRBQdKPSXd1:Li:::irii75.               ",
        "                    .Ii::vi..::...7J.        .7QgERRBbXJvii:ii7js                 ",
        "                    .bv77P7:.::ir7:            :7r7jY:D2irrLLY7.                  ",
        "                         .s::i::.                     77rri:.                     "
    };

    private static final String[] BULBASAUR = {
        "                                                                SBi   .:.         ",
        "                                                               SbLB7iUJBi         ",
        "                                                            .rRSiibBL:XQ  :.      ", 
        "                                         .i777ssYJvrirrJYSSPPXr::2M7:iQBIBB.      ",
        "                                    .iYuSj2sL7JJU111Iu1jjLLr77LuXui:i7R25Q.       ",
        "                                  7PqU7i::::irrriir77YYv77rr7sYviiiriUgJQK        ",
        "                                bQI7iirirr777i:75XK5uYLirrrr7iiirr7riKZLB.        ",
        "                              .BQ7i7r7r777rr:iPdLi:::::rr777r7r7r7rriRSuRj        ",
        "           7YYj7:             Bb57ir7r7iiiirbBZ7i:iirr7r7r7r77v77rrirDbsXB        ",
        "         .b7i77LUZQ2:rrjLYYJ:MBbbZjL7r7YUqIXXs:jB7iv77rrr7r7r7r7irir7PDYjQR       ",
        "         E7irrrJEUJY7rriririr:::r7j1UMZjv::...:.5R:77r7r777rv7riii771uDujJBu      ",
        "        dv:7ii::.............::::::::i:..::rrriirBvir7r7r7r7iiirivL1UuSgLuLBY     ",
        "       idrI::.:.::....:is1dZMMBb:irii:i:iiririii7KK:7r7rrrriri77sJS22uUMKjsLBY    ",
        "       BBI::.:.:...rjbdbbDbEEQI:irrriiirrriririr71Biirr777vsLJj52S25UI1IBUJsYBY   ",
        "       BY.:::::..XBbqXqqbbDMbr.:riiiiiri7irii:iivvQIvYjY11SIK5S2512U2uuLEZss2sB:  ",
        "     :d:.i::::...rDBgEbgMR1r.:irii:iirii:iiiii:r7YUBL52Iu5122IU2121Uu2juvBusJj2B  ",
        "    :b::::::::YUi::7bQMU7:::rii:iiiii:..::iii:irs7rBQJuJUUIUIU2uI1IU2UI1JqQ7LLYgB ",
        "    E7i7S.i7.BBB:i::.i:.:iiiiiiLiiiiir11:.:i:iiLLLigMZI1uIUIU5121I152I22juBs7YsJB ",
        "   SKr qB.s1.EBI:iri:.:::irii:57:irsv5BBBMi.::7vJL7SIidZIYUu2u212UI2IU2ju7BUJsUJgv",
        "  LB7 vBB:LI:iiiir:.:qQB:rri:P7..7b: BIbBBBi.r7uYj7sMiiuMDJuu2121211juJjYuduJUuUuu",
        "  BM  Bs7r7Li:iii::JBMMB::i:7M..LZ  qEU7 uBQ:rUuJ7viQ7YriqBqJLu12J1j1suj1jjs1j1sLd",
        " rBi KQr 1:iirii::bBEKgM.i:iii.iB   BqP   QBg7YJLL77d27UDdZBBbJsLusuj1uIS2Juj1ju7g",
        " jS  ZB: jiiriiii::7dDBu.:iii::Mr   BgB   BMB7v7LvY7PK7UBPK5bQBDS77LU5dbqjUu1u1JUZ",
        "rI7  UQi.1ii:i:iii:..rYi:iirirrR    BRBJ iBDQY7L7sv7suv7UBbPKPKZMQMdKEK1UUuUuUj2bq",
        "Q7:i rBSMri:::iiiii:i::iririr:vJ    BQZZuK51gL7LYLsYYLYL7IBbbKPKS2BQqJJj1JUJujULB.",
        "Pi:irLEDb.:::iiririririi:iiriivb    7BXbgMbEdrvJLjLJYsLs7rSBqbPdPbXMLgdJYuj1uUYBQ ",
        "Bbd1:. ..:i::iiiriiiriiii:iiriibXvi:iSjvv77:7UsLsYJYJLsvLvrqBgMEMDQB7rdBIYUjjKBB  ",
        " SBBDPsi.:.7.::i:rY::i:i:i:iii:::rri:...:rLUQK7sLYLJYJYjLJLvUKqdqqqI7LrUQbsdBB1   ",
        "  :5QbPdBIJr:::..:r...:.::::::::i:ir77YMgPqUj7JY751s1j1sJYYL7r7rri77Jssr7BBb7     ",
        "    :PZK5QBBQDXKII1KXPKPbddMgZbdbMdMBBuBsL7YLY7vZBYusY7L7svL7LLYvuujv77Y7sB       ",
        "      .i2SsSMZBbP2XXX5K5X5XXqXK5KqDMZUJrv7Lr7s2IKi7ii::irrLLj7LJPLr:.:vYJ75Q      ",
        "         .EPsuJK527ri::::::i:rL5bRKY7777ir72dDJi:::i:i:i:ir2Xr2bi..rJrrJvYrMK     ",
        "          1rjS5USSPXP2qXSIXX52UJ7ir7L7Yj5dEQU::::::ii:i:ii7sgUK.:sdMBMrvYLYLB     ",
        "          d7:::rrLubSqS515UI12YUSdqS5ZbbUPMX.::iLP5::iiii7rYBj.jEdK5SB7LLJYLg7    ",
        "          Ku:.:i757rLs1KZbDDEbbXbXSUIu2uYZM....KB5B7iii:77idB DR2u55PBJ7JLsvKd    ",
        "          iM jEZIEEirr7jPb1vr7sU122IU211uE.:7UX:SgBL:i:r7viBr.iQS15ddB17LjLvUB    ",
        "           QQXLJu1BL77L7sj5qPUX21suJjYULMDUX2UB::ii:i:i7L:5b.:.:gMRDBBPrJLJLZQ    ",
        "           :Br72jKQj7L7v77rvuBZqdQP512J1BI777ME.:::i:irL:LB77YL7rSRBMd7YYsYLQX    ",
        "            5BIPEB2:v7v7L777RL   7BQRMbQg7Ls2Bi:iii:irLijBBuJYuJY7vL7rLLssYrB:    ",
        "             QsrLr:77LvY7LrBu     .ZqUYBXSKSQD.i:i:irLiXBIQB7sLsLYLY7LLsLJ7DQ     ",
        "              g.:ir7L7Lvv7BP        BMMRPMBRM:::iir7vrMg   jBvYLsvv7LYYLsL5B      ",
        "              qB7SS7JXYYqBr         . 7Y.Li:.:::i777uBI     LQXj75Iv7u2YYbB.      ",
        "             .XB:rBQ27BKJ             bbr.rLr:vUYs5BQ.       bSQBMJBMZ2QMb        ",
        "               :   .:.               rX7dB:iQQSSB2u:         .  .r:s:7:i.         ",
        "                                         .s:..ir.                                 "
    };

    private static final String[] TOTODILE = {
        "                        ....:.                                                    ",
        "                       iiriv7svL.                                                 ",
        "                     iu:.:2Ds:i7U:                                                ",
        "                    .BL7711YLsiiiYi                                               ",
        "                    .MuYY777JIPY::Jv.                                             ",
        "                     ib2L2SdDBi:Zi:rvr.::::.:.                                    ",
        "                      :iBEgbbQ :BZLrirrii:7LvLqL.                                 ",
        "                      :XBEKbKdPMqMdL7ruQZEiL. .gs                                 ",
        "                       .QMPKbqdPbPMI77IBBBiXj .XD.                                ",
        "                        sQDbqPKbKPqMs7rbBBBB:.iQP.                                ",
        "                         bDdPKPqbqbPMLrrZPqL. JBb.                                ",
        "                         .PBbbqbKbKbbRsrrPv  .BBb.                                ",
        "                           XQPbKbqPqdbMs771i:BBPb.                                ",
        "                        :   BMbZddbdqdPZbjsubBb7b.                                ",
        "                   :B17EB  rBS5U5UI1UuSduY2J7r7LU   .7..7                         ",
        "                  7EZbERg1uRX5IS2I155Sbs7YvYLLvJZ   1L7iJi                        ",
        "                  rQXSZXBgdjY7LvsjIq7Xs7YLsLsLL7BQs77rrii7s                       ",
        "                  rQREMvYr:i:::::7rIqL7LvLLsLsJSXvrririrriL:                      ",
        "                   rBBbQ7.iir:ir:i:7S7v2ULYvJ5ji::iiriri77q                       ",
        "                     q: 7:iiiivr:rSriLgQS1jUS7:iiiiriir17:.                       ",
        "                      bib:::::i. 27.2QR5JjLSL.rii:ii:iL.                          ",
        "                      7bZbsJY2KMv::1Z1r7r7.v7::ii7::vB.                           ",
        "                       rv1KSuJLi7vPJriri:. .1rvYj77MBR.                           ",
        "                         :::Yr7Y7SLi::..    :M5JsQBB.                             ",
        "                            E:   :. .   .:iii1q7BP                                ",
        "                           77q. :. ..:iL77rr::::2Ms5r                             ",
        "                          r7.is r :r77r7rr7rv7:::BBB:                             ",
        "                         iv:::ijj7v7rr7:.L::.Is7:iR                               ",
        "                        7Y::::.i7iiL::27LEMK5:D:i:7b:                             ",
        "                       rR:.::::rii:UDZBBdbBMgv7r:ivJg.                            ",
        "                      :57:::iiririi:2QPgDKdKKK77i7YLSK       rv                   ",
        "                      Jr:iirrriririi.2b51UJjjS7IJJLjsD.     sBM                   ",
        "                     :quL:i:iiiiiii::.q2uJ1u1JJ51vsLjI     dBQd                   ",
        "                     rSIPYv777iririiii7bvsLsYs7XsYLY7Z:   MBdB2                   ",
        "                     .MYIjJLjLYLLLL7YYYqJ7YLY7LKLvLrUDg5:SBKbQL                   ",
        "                      jRYLYU7LvYLsLJYs7ubY7v7L22r77uP52PdDEZbB                    ",
        "                       LMbS5KuJ7L7LLYvLr1K5uuIUYjuKX21IU2jU5gQ                    ",
        "                         72ZBBBQS2LY777L7LSMEPSEdbSS55IXIS2SIbbZ7                 ",
        "                             :rIMEZbEbEbB: .rsSSDZQMRMQMMDMDd55ui                 ",
        "                                QdqbqbbbgB         .......                        ",
        "                               EQqbEZbbdB7                                        ",
        "                          .r7XMDsIK51KdBL                                         ",
        "                          B5Pbr.7j::r5Q:                                          ",
        "                          :qbRIKRMUbXU                                            "
    };

    private static final String[] SQUIRTLE = {
        "                            .:::i:i:.                                           ",
        "                        .:::.:.:..::::::.                                       ",
        "                     .vr:.....:::::::::i7YJ:                                    ",
        "                   :Ys.  ..::i:::::i:::::::7si                                  ",
        "                  vYr.:.::::i:::::riiii.:iiirsY                                 ",
        "                 .Mvi::i:::::::::..7..:2:iirii72.                               ",
        "                 ::7::::::::::::. dQ   QZ.iiiiriS                               ",
        "                :B1:.::::::::::: jBBbvKBK::irrir7I                              ",
        "                PBq.:::::::::::..BBBBQBbLi:i7r7rrSi                             ",
        "               .KR:.:::::::::::.rBBBBQii:7i7r7r7rjj                             ",
        "               vDv.::::::::::::.7DLbs:7 i7rrrr7rr72                             ",
        "              L:..::::::::.:::...iii:7r.7rirr7rrrv5                             ",
        "              bi:.:.::::i::::.... . ...irirr7r7rrj5                             ",
        "              jPsr:iiYjULYYJsjYL77rri7777JLrr7r7ib.                             ",
        "               s57JsJ77irr7r7r77v7LLjJJvL7rr7rri27                              ",
        "                r277r7r7r7rrrrirrriririririrrriYb                               ",
        "                 .sYr:rr7r7rririrrrrrrri7irrrrI::7                              ",
        "                   .r7::irrrr7r7r7r7r7r7r7irvJ: L1u.                            ",
        "                  ..r2E2777rrirrriririii7L52E:::bi75r                           ",
        "             :rL7L7:ijrriLLsYJLLLLLYvLsbuYv777LjZsrrLL                          ",
        "         .rL7ri:::.:Y...::::::i:rr7r:rKi. ..iiri7djjJsL                         ",
        "       :vY:..::::.7I     .:i::::.::.72.  .:::iiri7XrJXXr                        ",
        "  :..:L7:..::::::rJii..    .::i:i::rS.. .::.::r7r:XLiruQ:                       ",
        " .b77rir.::i::::iu   ::ri:::.....::b...:::::.:i7iiUbi7rsK                       ",
        "  :PrY1..::::.:.I.  .   ..:ibr::i:Zi..::::::::riiruLYr7iu7                      ",
        "  7jiLuj7:.:.:.7L  . . . . .s    .U..r7:.::::rii:I::U7:i:I                      ",
        ".qjsULLJjLLvL7rRr . . . ...:7 .. L7.Ji7I:.::iii:uj i2ri::1                      ",
        " .:::::7rLLL7rrqv. . ..... rr . :1.:irr7.i77ri:1L. 7Y7i::s.                     ",
        "               ::7 .....:. 7r  7U:rrrr7iiri:SrEU.. jv7r::s.                     ",
        "              .7 r:  . ... L.  u7LJUYLr77772siL:: .br7i:i5                      ",
        "               L .b:ri:::..7      ..:ij2L77:..L.: 7q7rriLB          ..:..       ",
        "               r 7:..:irii7b:i:rii::.:J .:.::.1i: iq77i7EZ     .:7YJ7v7LYu7:    ",
        "               Ys7 .... . .J..:::::::.7i:.:::.YL. :S77JUdi   .LYr::::::..:YUSi  ",
        "              rYR: ........s ..........77ii7777Mi: Is5uLK   71::.::::::::rr7rK: ",
        "             Y7.rJ  .......L........::i.Lqri::::r7iiE77Xr  vu:::::::::ir7r7r7rX ",
        "            57 ..7J. ......Y  .. .:iii:Y7...::::..:YS7sI .ujr7r7rrrssuYsv7r7r7Y7",
        "           rL ....7U:....  2. ..::i::.U7..::::::::.:QJj :5vr7r7rr7Is7r77J77r7rLr",
        "           5 ....:.iIL.:i7rS77ii::::.s7.::::::::::..7Bi77rr7rrrrrSiiirrrirr7r7Li",
        "          rY ...::::rJI7:::.:rYv7ri.71.::::::::::::.:qLirr7rriri1Uir7rrr7rrrriS.",
        "          vJ.::::::7ri7s7iii:::iirrrX1 :::.::::::::::2Liirrrrrii7X:rirrrrrrriJ2 ",
        "          is::iirirr7rriUd7i777rrir:ibi.::. .::::::.isJ:rr7rrrrirYurririrrrr2S  ",
        "          rU:rirr7r7rrrLs    ..:..i2Lubi::..:::::::iij1rr7r7r7r7riLSJL7r7s1Si   ",
        "        ij7i:irr777r77Lq               5::::::::::rrruK7U21ujLL77777uSdDZU:     ",
        "        i7Er7Lrr7vLUU51i               iSrrririrr777rI.  ..:rv7jJJYs7i..        ",
        "         :J.:PYj2J7:.                   5Y7777777r7rr2                          ",
        "             Li.                        :2i77777r7r7rS:                         ",
        "                                        :q7j2j7:iv5ss7D                         "
    };
 
    private static final String[] LAPRAS = {
        "                                 iivri                                            ",
        "                               :P1u2qDQ7    ::ir:                                 ",
        "                               b7sSbqbPBi :viir15qr                               ",
        "                           7qLvBX5urri7LSXi:rrL7r7XP                              ",
        "                           iK7IQj:.iirrrUX771Su5L7YQ7                             ",
        "                            XLrrYv77v77rjJrKbjJJgu1Qj                             ",
        "                           :5L777v7L7rirr7iXXuj1USEb                              ",
        "                          7L77LvvLs77i777r77d2IXqXr                               ",
        "                         7rv7v777Ir.RB:BjU11L1XZ                                  ",
        "                        .vLL7r7r7sv bBBEJ55jjsKU                                  ",
        "                        iKYj7Yvv777Y7USXKi.u1BB:                                  ",
        "                        .EESbbSUSu2ISs7i. :jKQ5                                   ",
        "                            :::riri:....:7251Q                                    ",
        "                                  . 7sKSS1bPEi                                    ",
        "                                    r1I2uU15S                                     ",
        "                                   iiIIJ111M:                                     ",
        "                                  ...dUUj2SE                                      ",
        "                                  v iu1uIjZ:                                      ",
        "                                 L  J7r77vS                                       ",
        "                                7. 7s7777Yj                                       ",
        "                               r: iUvvY21bJ   :2i:7.                              ",
        "                              i: iILJ1sr:.r77iI:i:1.                              ",
        "                             :. 7UvI1   .Y55jQrri7K                               ",
        "                            i..7YJ5J..7ss7i::i:i77bi    :.                        ",
        "                           r..s217r. .PKri:::ri:iLLKsurgDds                       ",
        "                          r::sb2Yi27.:r7jr7ir77:rvvi:r77r5U                       ",
        "                         i::iiujr:.KJY7jLi:iii::iii:::rJY1q:                      ",
        "                        7::L.L7..:iiiir7r::::ii:::777:i7: YZU                     ",
        "                       ii.L.7Pi77i::::::i::::iiriii7vr::r7u7YZ  .                 ",
        "                      .i:iv.di :1jr:::::i:ii7:i:irri7rr:71i:YuBdKK.               ",
        "                      vbdD:SiL7Y7SYi:i::::7Ij27::ir7irri::i7r7rj5M.               ",
        "                     .MM2Ki5.:77r7r:i:i::7r  .S1::ii7ir7vvL777ivB                 ",
        "                     IuijL.2ir::....:::::vU.:i7v7vi77L7v77rJuJ11j                 ",
        "                     2SiS: .irirJ7r::::::.sX7rrrv7L77rvrr77iri2Xd                 ",
        "                     uXv7U77vY7Yrr7X57i7ir:7i7irr77riir7r7777S27ID....            ",
        "          .:rLu2XSSU2jusj7JsuJ1JJY7:LIvi7rri77ririrrrirr777i77iiIPQJXSXur.        ",
        "       .ijIP22jjLLvL77rrr7r777rr72IS:iS1r777r77777r7r7r7r77777i75sDsYYvj1S1r      ",
        "      75Jiiii:iiiir77777Lvv77r7iEBqJb7:L27ri7r7rY7rirr77v777v77b75ULuuUYY7Lj5v:   ",
        "    :S7iii:i:i:::r7L7777777dq2Jjuq5YJP2iiYLs7LLLLY7vvsLL77irvJ2rSQJ511suu5ISUXbE1:",
        "   Yuiiii:iii:i:r7LvL7vvv7gLijI5UYubdUPdPsJLv7vr77viirLLu1uUXL:LBKI5KqPS277L5KqPg2",
        "  uL:iiiii:i:iiir7r7vsLJj7:i::.iJPX5JY7LLuKqSS2SIqqXUuvr::i7iiUbXYYsLjJU2d7       ",
        " 7L:iiri7r7rrr77L7LvLvvi.     suYv7irr7r7ir7uJ1j5UUU55qqSj1JIqZ2I5525UUjuJKX7     ",
        "77:sJjLv777v7777rvri..       s7i:i::irr77vrrr5IRXKSX5XIIUIISusb.i15K5SXb5XqDRBs   ",
        "BJI7i..                     g7::::i:irv7YLujIqS7:ivL1J2IK5X1uLXr  .:7vYLuJLrr7b.  ",
        "i:                         I7:i7LujU1SSqXbqKU7.     .iis2KqdPKJBr                 ",
        "                           qX5I7ii:...... .              .::rLuqK                 ",
        "                           .:                                                     "
    };

    private static final String[] MARIL = {
        "                                   .:::i:r::.                                     ",
        "                                 .v77i::irLLjvi                                   ",
        "                               .Lv...:.::::i:rv5.                .ir::.           ",
        "                              .7:.....:i7r7ri:iiU.             Lsrrr7jKSU.        ",
        "        .i7LLjJJY7.           Y::i::iuSKXPKbPXr:rU            27:irvvsLJUbv       ",
        "      .iiii.::r777Jji        vi:7i:sbX52IjJvvJbriu           JI7LLs7LLYLs755      ",
        "     .Y. ::::irririrY1       J.ri:Yb1U15JLr777juiS:.:i:.     qssLvLS5X5SSS7Sr     ",
        "    .s::::::iiiiiirii7u     :r:r:id1111vv7v7LruLYL::iirr77r.:PL77ud21JU11SbsI     ",
        "    77:::i:i:::iiiii:rd:    .L:r:2I211777L777Luvvi.:...:.::rY5uY7bJ1u21Ujj5KX     ",
        "    Jrri7ri:::iiriiirvDi     LiiiXI1UL77L777s1L77irii:::::::::vjXXUU2js77rvS5     ",
        "    2jiriiii:iiri7rv7JE:     :S7:Sq5s777r7Y1LL7Lriirr7i::::iii::uZUj77r7rrJZ7     ",
        "    iDY777777777L7vLsIS       .77i5Iurv7juY7YvLriiriririiiririi::7Xr77v77LMK      ",
        "     7b2YsLJLsLsLJLLUX          .JiYJ1JjjL7L7riiiriririrrrr7iriii:r2r77LIBS       ",
        "      :KPJLvLvYLsvU17          .::rirri:iiiiiii:irr:ririririririr::7PXEEb:        ",
        "        :sBbL5IXjLi.          :virii:i:i:iirii:rL.:L:iiriiiiiiii:7::Ui.           ",
        "          BY                 iL:7iiiririririri:BD  Bi:ririririL2 gQ:7             ",
        "           Bg               .s:riiiiiiiriiirir:RQBBB:iiririiii:BBBD:vr            ",
        "           BB i             s:rii:iiiiiiiiririi:jSU:::i:i:7rii:iIj::7L            ",
        "           bSZB7           .7:7vvLii:iiririririi:::i:LsL77rL77ii.::i7j            ",
        "             iB.           :77r..is77rriiiriririririi7LirJMKririi:irjs            ",
        "             ZB            rrLr:.iir7v7ririririririri7L::7si:riiirrLU7     ..     ",
        "             QB :.         :Uiuri:i:::r7riririrr7r77777JJ7rr7r77LLJLjXL7YvsvjK:   ",
        "             BBBBBi    .    UL7uLvr7r7surrr7r7rrii:::......::r7sJuJYISjIU1LLvZr   ",
        "            .QBs LB7   BBQd:jvLvYLJLL7777ii::..         ........::r27rdSSU55DJ    ",
        "             v    XBr LBi:MBBD7YLjJuL7ii.........:::::::::::.:.....1  .r7uY7:     ",
        "                   ZBLBZ    vQPJJL7::...:::::::::::::::::::.:.:..:J.              ",
        "                    bBQ       :Ev:..::.:::::::::::::::::.:.:.:..:j.               ",
        "                     bi         r:..:::::::::::::::::::::.:.:.:7r                 ",
        "                                vKi..:::::::::::::::::.:.:..:7r:                  ",
        "                              .qILI21i7i:::::::::::::::...::i.                    ",
        "                             .R2YJLPi .:irrrii:i:i:iii::iJ51                      ",
        "                             2Yr77jq       ....:i::.. UdIjuK7                     ",
        "                             5..:isb                  .EIU2M7                     ",
        "                             :U7LLX:                    rr7:                      ",
        "                               :::                                                "
    };

    public static String[] getTitulo() {
        return titulo;
    }

    private static String[] getArte(String nome){
        switch (nome) {
            case "Charmander":
                return CHARMANDER;
            case "Ho-oh":
                return HO_OH;
            case "Vulpix":
                return VULPIX;
            case "Magmar": 
                return MAGMAR;
            case "Pikachu":
                return PIKACHU;
            case "Ampharos":
                return AMPHAROS;
            case "Dedenne":
                return DEDENNE;
            case "Jolteon":
                return JOLTEON;
            case "Bayleef":
                return BAYLEEF;
            case "Treecko":
                return TREECKO;
            case "Shaymin":
                return SHAYMIN;
            case "Bulbasaur":
                return BULBASAUR;
            case "Totodile":
                return TOTODILE;
            case "Squirtle":
                return SQUIRTLE;
            case "Lapras":
                return LAPRAS;
            case "Maril":
                return MARIL;
            default:
                break;
        }
        return CHARMANDER;
    }

    public static void imprimirArte(String nome){
        String[] arte = getArte(nome);
        for(int i = 0; i < arte.length; i++){
            System.out.println(arte[i]);
        }
    }

}